import {backgroundHero} from './backgroundHero.js';
import {backgroundMedia} from '../data/backgroundMedia.js';
import {applicationMedia} from '../data/applicationMedia.js';
import {solutions} from '../data/industries.js';
import {company} from '../data/company.js';
import {esc,icon,link,quote} from './ui.js';
import {form} from './forms.js';
import {contactActions} from './contactActions.js';

export function applicationPhoto(key,alt,{priority=false,sizes='(max-width:767px) 90vw, 45vw'}={}){
 const m=applicationMedia[key];return `<img src="${m.src}" srcset="${m.srcset}" sizes="${sizes}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" loading="${priority?'eager':'lazy'}" decoding="async" ${priority?'fetchpriority="high"':''}>`;
}
const copy={
 'beverage-service':['Paper and plastic cup formats for beverage service requirements.','Disposable cups for beverage service in a café setting'],
 'catering-events':['Tableware and foodservice packaging for catering, functions and event service.','Plates, bowls and cutlery in an event catering setting'],
 'institutional-foodservice':['Packaging formats for organised and institutional meal service.','Meal trays and food containers in an organised foodservice setting'],
 'custom-branding':['Discuss branding and packaging requirements for your business.','Cups, bags and boxes illustrating packaging branding requirements'],
 'takeaway-delivery':['Food packaging for takeaway, delivery and on-the-go service.','Food containers and carry packaging at a takeaway dispatch area'],
 'bakery':['Packaging solutions for cakes, pastries and bakery products.','Cake boxes and pastry containers in a bakery setting'],
 'sweets-confectionery':['Packaging solutions for sweets, confectionery and traditional food products.','Sweet boxes and confectionery containers in a sweets shop setting'],
 'restaurants-qsr':['Packaging for dine-in support, takeaway and quick-service requirements.','Cups, meal containers and portion cups at a restaurant service counter']
};
export function solutionsLanding(){return `<section class="wrap solutions-hero"><div><p class="eyebrow">OUR SOLUTIONS</p><h1>Foodservice starts with the application.</h1><p class="lede">Explore packaging solutions for beverage, takeaway, catering, bakery, sweets and institutional requirements.</p></div><figure>${applicationPhoto('solutionsHero','Tableware and food packaging arranged for foodservice applications',{priority:true})}</figure></section><section class="wrap solutions-discovery" aria-label="Explore application solutions"><div class="solution-visual-grid">${solutions.filter(s=>copy[s.slug]).map((s,i)=>`<a class="solution-visual-card" href="/solutions/${s.slug}"><div class="solution-scene">${applicationPhoto(s.slug,copy[s.slug][1])}</div><div class="solution-card-copy"><span class="index">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(s.name)}</h2><p>${copy[s.slug][0]}</p><span class="text-link">Explore Solution ${icon()}</span></div></div></a>`).join('')}</div><p class="caption solutions-note">Available formats and product suitability can be discussed with our team based on your requirement.</p></section><section class="wrap solutions-end"><div><p class="eyebrow">FIND YOUR FORMAT</p><h2>Not sure which format fits your requirement?</h2><p>Tell us what you are serving, packing or distributing.</p></div>${quote('Discuss Your Requirement','','Product enquiry').replace('data-quote=', 'data-source="solutions" data-quote=')}</section>`;}

export function contactPage(){return `${backgroundHero({media:backgroundMedia.contact,kind:'contact',position:'center',content:`<div class="background-hero-copy"><p class="eyebrow">CONTACT SK THERMOFORMERS</p><h1>Let us discuss your requirement.</h1><p class="lede">Bulk supply, product requirements, custom paper cup enquiries and international business enquiries.</p><div class="contact-actions">${contactActions()}${link('Send an Enquiry','#business-enquiry','button outline').replace('href=', 'data-event="rfq_click" data-enquiry-scroll href=')}</div></div>`})}<section class="wrap contact-workspace contact-panel-composition" id="business-enquiry"><aside class="contact-details"><p class="eyebrow">DIRECT CONTACT</p><h2>${esc(company.legalName)}</h2><a class="contact-link" data-event="call_click" href="tel:+919414015833">${esc(company.phone)}</a><a class="contact-link" href="mailto:${company.email}">${company.email}</a><div class="contact-actions">${contactActions({compact:true})}</div><h3>Address</h3><address>${esc(company.address)}</address>${link('View Location','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(company.address))}<p class="contact-brief">Share the product, application and estimated quantity. We can discuss the details around your buying brief.</p></aside><div><p class="eyebrow">SEND A BUSINESS ENQUIRY</p><h2>Tell us what you need.</h2>${form('General enquiry','','contact')}</div></section><section class="wrap contact-process"><p class="eyebrow">TELL US WHAT YOU NEED</p><ol>${[['Share Your Requirement','Product and application.'],['Product & Quantity Discussion','Formats and buying volumes.'],['Specification Discussion','Details for your intended use.'],['Commercial Discussion','Packing and supply requirements.']].map(([h,p],i)=>`<li><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol></section><section class="wrap contact-end"><div><h2>Have a packaging requirement in mind?</h2><p>Talk to our team about products, quantities and application requirements.</p></div><div class="contact-actions">${contactActions()}${link('Send an Enquiry','#business-enquiry','button outline').replace('href=', 'data-event="rfq_click" href=')}</div></section>`;}
