import {familyBand} from './productStory.js';
import {company} from '../data/company.js';import {exportData as data} from '../data/export.js';import {categories} from '../data/products.js';import {esc,photo,link,heading,breadcrumb,icon} from './ui.js';import {categoryCard} from './catalogue.js';import {form} from './forms.js';
export function exportPage(){const documents=data.documents.filter(d=>d.verified&&d.document);return `<section class="wrap export-hero">${breadcrumb([{name:'Export'}])}<div class="export-hero-grid"><div><p class="eyebrow">SKP / INTERNATIONAL BUYER ENQUIRIES</p><h1>Packaging Solutions<br>for Global Buyers.</h1><p class="lede">${esc(data.description)}</p><div class="actions">${link('Send Export Enquiry','#export-enquiry','button')}${link('Explore Product Range','/products','button outline')}</div>${company.catalogue?link('Download Catalogue',company.catalogue):''}<p class="caption">M/s S. K. Thermoformers / Khairthal, Rajasthan, India</p></div><figure class="export-composition">${photo('hero','Broad SKP presentation of beverage cups, plates, bowls, cutlery and containers',{priority:true,sizes:'(max-width:768px) 92vw, 55vw'})}<div class="export-visual-footer"><span>PRODUCT SELECTION</span><span>SPECIFICATION DISCUSSION</span></div></figure></div></section>
<section class="wrap export-product-band">${familyBand(['food-containers','bagasse','kraft-packaging','aluminium-foil'])}</section><section class="muted-surface section"><div class="wrap buyer-profiles">${heading('WHO WE WELCOME','A sourcing conversation for your business.','We welcome enquiries from importers, distributors and procurement teams.')}<ul>${data.buyers.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></div></section>
<section class="wrap section">${heading('THE PRODUCT PORTFOLIO','Explore the formats behind your brief.','Browse tableware, takeaway and packaging formats for your sourcing brief.')}<div class="export-range-grid">${data.portfolio.map(slug=>categoryCard(categories.find(c=>c.slug===slug))).join('')}</div><div class="section-bottom">${link('Explore Complete Range','/products')}</div></section>
<section class="charcoal-surface section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">PRIVATE LABEL & CUSTOM REQUIREMENTS</p><h2>Your brand.<br>Your buying brief.</h2></div><p>Talk to us about brand printing, product selection, sizes, packing and destination-specific requirements. Paper cup printing is a documented enquiry capability; private-label and other custom scope require a feasibility review.</p></div><div class="custom-topics"><span>Brand artwork</span><span>Product selection</span><span>Packing requirements</span><span>Bulk quantities</span><span>Destination requirements</span></div>${link('Discuss Your Custom Requirement','#export-enquiry','button')}</div></section>
<section class="wrap section">${heading('THE SOURCING DISCUSSION','From requirement to agreed responsibilities.','A suggested discussion sequence. Sampling, production, packing and shipping scope depend on the selected product and agreed commercial terms.')}<ol class="export-journey">${data.journey.map(([title,text],i)=>`<li><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(title)}</h3><p>${esc(text)}</p></li>`).join('')}</ol></section>
<section class="muted-surface section"><div class="wrap export-assurance"><article><p class="eyebrow">SPECIFICATION & QUALITY</p><h2>Define the evidence you need.</h2><p>Discuss material construction, product dimensions, sample review, packing configuration and quality requirements for the destination.</p>${link('Quality & Product Information','/quality')}</article><article><p class="eyebrow">DOCUMENTATION & COMPLIANCE</p><h2>Review requirements by destination.</h2><p>Documentation requirements can be discussed based on product and destination. Ask which declarations, reports and commercial documents can be supplied for the agreed order.</p>${documents.map(d=>link(d.name,d.document)).join('')}<p class="caption">Product-specific evidence and applicable requirements should be confirmed before commercial approval.</p></article></div></section>
<section class="wrap section export-enquiry-layout" id="export-enquiry"><aside><p class="eyebrow">EXPORT ENQUIRY</p><h2>Send a clear sourcing brief.</h2><p>Tell us your product format, destination and estimated quantity. Technical details can be discussed with the team.</p><p>MOQ, samples, lead time, Incoterms and packing data are confirmed for your requirement.</p><a class="contact-link" href="mailto:${company.email}">${company.email}</a><a class="contact-link" href="tel:${company.phone.replaceAll(' ','')}">${company.phone}</a></aside><div>${form('Export enquiry','','export')}</div></section>`;}
