import {visualDetail} from './visualDetail.js';
import {industryExperiences,industriesLandingMedia} from '../data/industryExperience.js';
import {categories} from '../data/products.js';
import {esc,icon,link,quote,breadcrumb,heading} from './ui.js';
import {backgroundHero} from './backgroundHero.js';
import {categoryCard} from './catalogue.js';
import {form} from './forms.js';
const contextQuote=(industry,label='Discuss Requirement')=>quote(label,'','Domestic bulk').replace('data-quote=',`data-industry="${esc(industry.ctaContext)}" data-quote=`);
function scene(industry){const m=industry.cardImage;return `<img src="${m.src}" srcset="${m.srcset}" sizes="(max-width:767px) 90vw, (max-width:1150px) 45vw, 30vw" width="${m.width}" height="${m.height}" loading="lazy" decoding="async" alt="${esc(industry.imageAlt)}">`;}
export function industryDiscovery(){return `${backgroundHero({media:industriesLandingMedia,kind:'industries',position:'65% center',content:`<div class="background-hero-copy"><p class="eyebrow">INDUSTRIES WE SERVE</p><h1>Packaging solutions across foodservice industries.</h1><p class="lede">Explore packaging requirements across restaurants, hospitality, catering, institutions, retail and distribution.</p><div class="actions">${link('Explore Industries','#industry-ranges','button')}</div></div>`})}<section class="wrap industry-discovery-section" id="industry-ranges" aria-label="Explore industries"><div class="industry-visual-grid">${industryExperiences.map(m=>`<a class="industry-visual-card industry-connected-card" style="--card-ratio:${m.cardImage.width/m.cardImage.height}" href="/industries/${m.slug}"><div class="industry-card-scene">${scene(m)}</div><div class="industry-card-content"><h2>${esc(m.title)}</h2><p>${esc(m.shortDescription)}</p><span class="text-link">Explore relevant products ${icon()}</span></div></a>`).join('')}</div></section><section class="wrap industry-closing"><h2>Tell us how your business serves food.</h2><p>Share your application, product formats and quantities. We can discuss the details around your requirement.</p>${quote('Discuss Your Requirement','','Industry enquiry')}</section>`;}
export function industryDetail(path){const industry=industryExperiences.find(m=>path==='/industries/'+m.slug);return industry?visualDetail(industry,'industry'):null;}
