import {industryExperiences,industriesLandingMedia} from '../data/industryExperience.js';
import {categories} from '../data/products.js';
import {esc,icon,link,quote,breadcrumb,heading} from './ui.js';
import {backgroundHero} from './backgroundHero.js';
import {categoryCard} from './catalogue.js';
import {form} from './forms.js';
const contextQuote=(industry,label='Discuss Requirement')=>quote(label,'','Domestic bulk').replace('data-quote=',`data-industry="${esc(industry.ctaContext)}" data-quote=`);
function scene(industry){const m=industry.cardImage;return `<img src="${m.src}" srcset="${m.srcset}" sizes="(max-width:767px) 90vw, (max-width:1150px) 45vw, 30vw" width="${m.width}" height="${m.height}" loading="lazy" decoding="async" alt="${esc(industry.imageAlt)}">`;}
export function industryDiscovery(){return `${backgroundHero({media:industriesLandingMedia,kind:'industries',position:'65% center',content:`<div class="background-hero-copy"><p class="eyebrow">INDUSTRIES WE SERVE</p><h1>Packaging solutions across foodservice industries.</h1><p class="lede">Explore packaging requirements across restaurants, hospitality, catering, institutions, retail and distribution.</p><div class="actions">${link('Explore Industries','#industry-ranges','button')}</div></div>`})}<section class="wrap industry-discovery-section" id="industry-ranges" aria-label="Explore industries"><div class="industry-visual-grid">${industryExperiences.map(m=>`<a class="industry-visual-card industry-connected-card" style="--card-ratio:${m.cardImage.width/m.cardImage.height}" href="/industries/${m.slug}"><div class="industry-card-scene">${scene(m)}</div><div class="industry-card-content"><h2>${esc(m.title)}</h2><p>${esc(m.shortDescription)}</p><span class="text-link">Explore relevant products ${icon()}</span></div></a>`).join('')}</div></section><section class="wrap industry-closing"><h2>Tell us how your business serves food.</h2><p>Share your application, product formats and quantities. We can discuss the details around your requirement.</p>${quote('Discuss Your Requirement','','Industry enquiry')}</section>`;}
export function industryDetail(path){const industry=industryExperiences.find(m=>path==='/industries/'+m.slug);if(!industry)return null;
 const hero=backgroundHero({media:industry.heroImage,kind:'industry-detail',position:industry.heroPosition,overlay:industry.heroOverlay,content:`<div class="background-hero-copy">${breadcrumb([{name:'Industries',href:'/industries'},{name:industry.title}])}<p class="eyebrow">INDUSTRY SOLUTIONS</p><h1>${esc(industry.title)}</h1><p class="lede">${esc(industry.shortDescription)}</p><div class="actions">${link('Explore Products','#relevant-products','button')}${contextQuote(industry)}</div></div>`});
 return `${hero}<section class="wrap section industry-requirements"><div><p class="eyebrow">INDUSTRY REQUIREMENTS</p><h2>Plan around your operation.</h2><p>${esc(industry.requirement)}</p></div><div class="industry-buying-brief"><h3>Include in your enquiry</h3><p>${esc(industry.brief)}.</p></div></section><section class="muted-surface section" id="relevant-products"><div class="wrap">${heading('RELEVANT PRODUCT FAMILIES','Explore formats for your business.')}<div class="category-grid">${categories.filter(c=>!c.legacy&&industry.productCategories.includes(c.slug)).map(c=>categoryCard(c).replaceAll('href="/products/'+c.slug+'"','href="/products/'+c.slug+'?industry='+encodeURIComponent(industry.ctaContext)+'"')).join('')}</div></div></section><section class="wrap section industry-application"><div><p class="eyebrow">APPLICATION & SERVICE</p><h2>${esc(industry.applicationTitle)}</h2><p>Tell us how the product will be served, packed or distributed. Bring your quantities, packing preferences and any custom requirements into the discussion.</p><div class="actions">${contextQuote(industry,'Request a Quote')}${link('Contact the team','/contact?industry='+encodeURIComponent(industry.ctaContext),'button outline')}</div></div><figure>${scene(industry)}</figure></section><section class="wrap industry-enquiry" id="industry-enquiry"><div><p class="eyebrow">BULK & CUSTOM REQUIREMENTS</p><h2>Discuss your industry requirement.</h2><p>Share the details your business needs.</p></div><div>${form('Domestic bulk','','industry-'+industry.slug).replace('name="industry" value=""','name="industry" value="'+esc(industry.ctaContext)+'"').replace('<strong data-industry-name></strong>','<strong data-industry-name>'+esc(industry.ctaContext)+'</strong>').replace('class="rfq-industry-context" hidden','class="rfq-industry-context"')}</div></section>`;
}
