import {homeHero} from './homeHero.js';
import {productUniverse,familyBand} from './productStory.js';
import {verifiedTrust} from './verifiedTrust.js';
import {company,customJourney,enquiryTypes} from '../data/company.js';import {primaryCategories,categories,listedProducts,homeCategories} from '../data/products.js';import {markets,industries,solutions} from '../data/industries.js';import {pages,legalPages} from '../data/pages.js';import {esc,photo,quote,link,heading,pageHero,cta,factoryPanel,breadcrumb,icon} from './ui.js';import {catalogueSources} from '../data/productMedia.js';import {categoryCard,productCard} from './catalogue.js';import {form} from './forms.js';
const journey=()=>`<ol class="journey">${customJourney.map(([name,text],i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(name)}</h3><p>${esc(text)}</p></li>`).join('')}</ol>`;
const pathwayCards=()=>`<div class="pathway-grid">${enquiryTypes.filter(x=>x!=='General enquiry').map(x=>`<a href="/rfq?kind=${encodeURIComponent(x)}"><span>${esc(x)}</span>${icon()}</a>`).join('')}</div>`;
const applicationCards=(compact=false)=>`<div class="application-grid ${compact?'home-applications':''}">${(compact?solutions.filter(s=>['restaurants-qsr','catering-events','takeaway-delivery','bakery','mithai-halwai','distributors'].includes(s.slug)):solutions).map((s,i)=>`<a href="/solutions/${s.slug}"><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><span class="text-link">Explore solutions ${icon()}</span></a>`).join('')}</div>`;
export function home(){return `${homeHero()}
 <section class="wrap section">${heading('01 / PRODUCT DISCOVERY','Explore Our Product Range','Discover tableware, containers and packaging around your foodservice requirement.')}<div class="category-grid">${homeCategories.map(categoryCard).join('')}</div><div class="section-bottom">${link('Browse All Products','/products')}${link('Custom Printed Products','/products/custom-products')}</div></section>
 ${productUniverse()}<section class="muted-surface section"><div class="wrap why-layout"><div><p class="eyebrow">02 / WHY SKP</p><h2>Manufacturing focus.<br>A practical supply conversation.</h2><p>Based in Khairthal, Rajasthan, M/s S. K. Thermoformers brings together paper cup manufacturing and a broad disposable foodservice portfolio.</p>${link('About the Company','/about')}</div><div class="credibility-grid">${[['Product breadth','Compare paper and plastic beverage formats, tableware and paper service essentials.'],['Custom requirements','Discuss paper cup designs, sizes and packing against your brief.'],['Specification first','Agree the application, product details and documentation before ordering.'],['Business enquiries','Bring quantities, destination and commercial requirements into one discussion.']].map(([t,d])=>`<article><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></div></section>
 <section class="wrap section">${heading('03 / APPLICATIONS','Start with the way you serve.','Find relevant formats for your operation, then define the buying requirement.')} ${applicationCards(true)}<div class="section-bottom">${link('Markets We Serve','/industries')}</div></section>
 <section class="wrap section home-materials">${heading('MATERIAL DIRECTIONS','Compare the construction behind the format.','Explore leaf, fibre, paper and wood formats. Review material construction and suitability for your intended use.')}${familyBand(['bagasse','areca','kraft-packaging','wooden-bamboo'])}${link('Material Responsibility','/sustainability')}</section><section class="manufacturing section"><div class="wrap split"><div><p class="eyebrow">04 / MANUFACTURING</p><h2>A clear specification connects the process.</h2><p>Paper cup manufacturing is our production focus. Discuss material construction, forming, printing and packing requirements for your selected cup.</p><p>Production details and manufacturing scope for other products are confirmed with the team.</p>${link('Explore Manufacturing','/manufacturing','button outline')}</div>${factoryPanel()}</div></section>
 <section class="wrap section custom-feature"><div class="split"><figure class="custom-visual">${photo('cup-print','SKP printed cup range')}</figure><div><p class="eyebrow">05 / CUSTOM SOLUTIONS</p><h2>Made around your requirement.</h2><p>Share the application, size, artwork and quantity. We will discuss paper cup design, printing and packing feasibility against your brief.</p>${quote('Discuss a Custom Requirement','','Custom requirement')}</div></div>${journey()}</section>
 <section class="muted-surface section"><div class="wrap assurance-grid"><article><p class="eyebrow">06 / QUALITY</p><h2>Agree what good looks like.</h2><p>Request material details, dimensions and application-specific evidence. Define sample and packing requirements before approval.</p>${link('Our Quality Approach','/quality')}</article><article><p class="eyebrow">07 / MATERIAL CHOICES</p><h2>Facts before environmental claims.</h2><p>Construction, use and local recovery infrastructure matter. Ask for product-specific information when comparing paper and plastic.</p>${link('Responsible Material Selection','/sustainability')}</article></div></section>
 <section class="wrap section"><div class="section-head"><div><p class="eyebrow">08 / B2B & EXPORT</p><h2>A direct route to your next enquiry.</h2></div><p>For domestic bulk requirements and export enquiries, talk to our team. Availability, documentation and commercial terms are confirmed against your brief.</p></div><div class="home-export-feature"><div><p class="eyebrow">INTERNATIONAL BUYER ENQUIRIES</p><h3>Bring your sourcing brief to SKP.</h3><p>Discuss product selection, private-label requirements, packing and documentation for your destination.</p>${link('Explore Export Enquiries','/export','button')}</div><figure>${photo('foil-rectangular','Foil packaging visual reference')}</figure></div></section>${cta()}`;}
const editorial=(sections)=>`<div class="editorial-grid">${sections.map(([title,text],i)=>`<article><span class="index">${String(i+1).padStart(2,'0')}</span><h2>${esc(title)}</h2><p>${esc(text)}</p></article>`).join('')}</div>`;
export function general(slug){const p=pages[slug];let extra='';
 if(slug==='about')extra=`<section class="company-facts"><p class="eyebrow">COMPANY INFORMATION</p><dl><div><dt>Legal identity</dt><dd>${company.legalName}</dd></div><div><dt>Product brand</dt><dd>SKP</dd></div><div><dt>Location</dt><dd>Khairthal, Alwar, Rajasthan, India</dd></div><div><dt>Manufacturing focus</dt><dd>Paper cups</dd></div></dl></section>${verifiedTrust()}${company.leadership.length?`<section><h2>Leadership</h2><div class="editorial-grid">${company.leadership.map(person=>`<article><h3>${esc(person.name)}</h3><p>${esc(person.role)}</p></article>`).join('')}</div></section>`:''}${company.history.length?`<section><h2>Company story</h2>${company.history.map(x=>`<p>${esc(x)}</p>`).join('')}</section>`:''}${company.milestones.length?`<section><h2>Milestones</h2><ul>${company.milestones.map(x=>`<li>${esc(x.year)} - ${esc(x.description)}</li>`).join('')}</ul></section>`:''}<section class="values"><h2>A straightforward way to work.</h2><p>Clear specifications. Product-specific information. Agreed commercial terms. These are the principles behind the buying conversation.</p></section>`;
 if(slug==='manufacturing')extra=`<section class="split manufacturing-feature">${factoryPanel()}<div><p class="eyebrow">YOUR PRODUCTION DISCUSSION</p><h2>Ask the questions behind the product.</h2><ul class="checklist"><li>What construction is appropriate for the application?</li><li>Which capacity and dimensions are available?</li><li>What printing and packing options are feasible?</li><li>Which production details and documents can be shared?</li></ul>${quote('Discuss Manufacturing','','General enquiry')}</div></section><section class="workflow"><h2>From brief to agreed supply.</h2>${journey()}<p class="caption">Share your brief to start the discussion.</p></section>`;
 if(slug==='custom-solutions')extra=`<section class="workflow"><h2>The requirement journey</h2>${journey()}</section><section class="form-section"><p class="eyebrow">CUSTOM ENQUIRY</p><h2>Share your brief.</h2>${form('Custom requirement','','custom')}</section>`;
 if(slug==='quality')extra=`<section class="documentation-panel"><h2>Request evidence for your application.</h2><p>Ask about current product-specific reports and documentation. Requirements vary by application; confirm the available evidence before approving your order.</p>${company.certifications.filter(c=>c.verified&&c.document).map(c=>link(c.name,c.document)).join('')}${quote('Request Product Documentation','','Specification request')}</section>`;
 if(slug==='sustainability')extra=`<section class="documentation-panel"><h2>Ask about the specific product.</h2><p>Bring your material requirements and local disposal context into the enquiry. Recycling or composting claims need evidence for the exact construction and relevant infrastructure.</p>${quote('Discuss Material Requirements','','Product enquiry')}</section>`;
 if(slug==='export')extra=`${pathwayCards()}<section class="form-section"><h2>Send your sourcing requirement.</h2>${form('Export enquiry','','export')}</section>`;
 if(slug==='resources')extra=`<section class="reference-library"><h2>Explore complete range visuals</h2><p>Browse complete compositions alongside our product-family pages.</p><label for="reference-catalogue">Choose a range<select id="reference-catalogue">${catalogueSources.map(c=>`<option value="catalogue-${c.id}">${esc(c.family)} / ${c.id}</option>`).join('')}</select></label><button class="button outline" id="open-reference-catalogue" type="button">View Complete Range ${icon()}</button></section>`+`<section class="documentation-panel"><h2>Need the current catalogue?</h2><p>Request the latest product availability and specifications directly from the team.</p>${company.catalogue?link('Download Catalogue',company.catalogue,'button'):quote('Request Catalogue','','Catalogue request')}</section>`;
 return `${pageHero('SKP / '+slug.replaceAll('-',' '),p.title,p.intro)}<section class="wrap section">${editorial(p.sections)}${extra}</section>${cta()}`;
}
export function industryPage(path){const item=industries.find(i=>path==='/industries/'+i.slug);if(!item)return `${pageHero('MARKETS & BUYING REQUIREMENTS','Markets We Serve','Explore product requirements by business type. Find the formats that fit your operation.')}<section class="wrap section"><div class="market-grid">${markets.map(i=>`<a href="/industries/${i.slug}"><h2>${esc(i.name)}</h2><p>${esc(i.description)}</p><span class="text-link">Explore relevant products ${icon()}</span></a>`).join('')}</div></section>${cta()}`;
 return `${pageHero(item.active?'MARKETS WE SERVE':'SPECIAL REQUIREMENT ENQUIRY',item.name,item.description)}<section class="wrap section"><div class="buyer-brief"><div><p class="eyebrow">THE BUYING REQUIREMENT</p><h2>Plan around your operation.</h2><p>${esc(item.detail)}</p></div><aside><h3>Include in your enquiry</h3><p>${esc(item.brief)}.</p>${quote('Discuss Your Requirement','','Industry enquiry')}</aside></div>${heading('RELEVANT RANGE','Explore the product families')}<div class="category-grid">${categories.filter(c=>!c.legacy&&item.categories.includes(c.slug)).map(categoryCard).join('')}</div></section>${cta()}`;
}
export function solutionPage(path){const s=solutions.find(x=>path==='/solutions/'+x.slug);return s?`${pageHero('APPLICATION SOLUTIONS',s.name,s.description)}<section class="wrap section"><div class="buyer-brief"><div><h2>Build the brief around the application.</h2><p>${esc(s.detail)}</p></div><aside><h3>Next step</h3><p>Share the format, volume and destination. Confirm suitability and current specifications with our team.</p>${quote('Discuss Your Requirement','','Product enquiry')}</aside></div><div class="category-grid">${categories.filter(c=>s.categories.includes(c.slug)).map(categoryCard).join('')}</div></section>${cta()}`:`${pageHero('APPLICATION SOLUTIONS','Foodservice starts with the application.','Explore beverage, takeaway, catering, bakery, mithai and institutional requirements. Product suitability and availability are confirmed with the team.')}<section class="wrap section">${applicationCards()}</section>${cta()}`;}
export function contact(){return `${pageHero('CONTACT SK THERMOFORMERS','Let us discuss your requirement.','Bulk supply, product specifications, custom paper cup requirements and export enquiries.')}<section class="wrap section contact-layout"><aside class="contact-details"><p class="eyebrow">DIRECT CONTACT</p><h2>${company.legalName}</h2><a href="tel:${company.phone.replaceAll(' ','')}" class="contact-link">${company.phone}</a><a href="mailto:${company.email}" class="contact-link">${company.email}</a><h3>Address</h3><address>${company.address}</address>${link('View Location','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(company.address))}<h3>Additional contact numbers</h3>${company.phones.slice(1).map(p=>`<a class="contact-link" href="tel:${p.replaceAll(' ','')}">${p}</a>`).join('')}${company.whatsapp?link('WhatsApp','https://wa.me/'+company.whatsapp.replace(/\D/g,''),'button'):''}</aside><div><h2>Send a business enquiry.</h2>${form('General enquiry','','contact')}</div></section>`;}
export const rfq=()=>`${pageHero('REQUEST A QUOTE','Start with your requirement.','Tell us the product, application, estimated quantity and destination. You can leave technical fields blank if you need guidance.')}<section class="wrap section rfq-layout"><aside><h2>A useful buying brief</h2><ul class="checklist"><li>Product or service format</li><li>Intended application</li><li>Approximate quantities</li><li>Material or artwork requirements</li><li>Delivery destination</li></ul><p>Prefer to talk directly?</p><a class="contact-link" href="tel:${company.phone.replaceAll(' ','')}">${company.phone}</a><a class="contact-link" href="mailto:${company.email}">${company.email}</a></aside><div>${form()}</div></section>`;
export function legal(slug){const p=legalPages[slug];return `${pageHero('WEBSITE INFORMATION',p.title,p.intro)}<section class="wrap section legal-content">${p.sections.map(([h,t])=>`<section><h2>${esc(h)}</h2><p>${esc(t)}</p></section>`).join('')}<p>Contact: <a href="mailto:${company.email}">${company.email}</a></p></section>`;}
export const notFound=()=>`<section class="wrap section not-found"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>Let us get you to the right place.</h1><p class="lede">This page is unavailable. Explore the product range or contact the team about your requirement.</p><div class="actions">${link('Explore Products','/products','button')}${link('Contact Us','/contact','button outline')}</div></section>`;
