import {solutionExperiences} from '../data/solutionExperience.js';
import {visualDetail} from './visualDetail.js';
import {industryDiscovery,industryDetail} from './industryDiscovery.js';
import {solutionsLanding,contactPage} from './applicationPages.js';
import {homeGateway} from './homeGateway.js';
import {editorialPage} from './editorialPages.js';
import {immersive} from './immersive.js';
import {homeHero} from './homeHero.js';
import {productUniverse,familyBand} from './productStory.js';
import {verifiedTrust} from './verifiedTrust.js';
import {company,customJourney,enquiryTypes} from '../data/company.js';import {primaryCategories,categories,listedProducts,homeCategories} from '../data/products.js';import {markets,industries,solutions} from '../data/industries.js';import {pages,legalPages} from '../data/pages.js';import {esc,photo,quote,link,heading,pageHero,cta,factoryPanel,breadcrumb,icon} from './ui.js';import {catalogueSources} from '../data/productMedia.js';import {categoryCard,productCard} from './catalogue.js';import {form} from './forms.js';
const journey=()=>`<ol class="journey">${customJourney.map(([name,text],i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(name)}</h3><p>${esc(text)}</p></li>`).join('')}</ol>`;
const pathwayCards=()=>`<div class="pathway-grid">${enquiryTypes.filter(x=>x!=='General enquiry').map(x=>`<a href="/rfq?kind=${encodeURIComponent(x)}"><span>${esc(x)}</span>${icon()}</a>`).join('')}</div>`;
const applicationCards=(compact=false)=>`<div class="application-grid ${compact?'home-applications':''}">${(compact?solutions.filter(s=>['restaurants-qsr','catering-events','takeaway-delivery','bakery','sweets-confectionery','distributors'].includes(s.slug)):solutions).map((s,i)=>`<a href="/solutions/${s.slug}"><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><span class="text-link">Explore solutions ${icon()}</span></a>`).join('')}</div>`;
export const home=homeGateway;
const editorial=(sections)=>`<div class="editorial-grid">${sections.map(([title,text],i)=>`<article><span class="index">${String(i+1).padStart(2,'0')}</span><h2>${esc(title)}</h2><p>${esc(text)}</p></article>`).join('')}</div>`;
export function general(slug){if(['manufacturing','custom-solutions','quality'].includes(slug))return editorialPage(slug);const p=pages[slug];let extra='';
 if(slug==='about')extra=`<section class="company-facts"><p class="eyebrow">COMPANY INFORMATION</p><dl><div><dt>Legal identity</dt><dd>${company.legalName}</dd></div><div><dt>Product brand</dt><dd>SKP</dd></div><div><dt>Location</dt><dd>Khairthal, Alwar, Rajasthan, India</dd></div><div><dt>Manufacturing focus</dt><dd>Paper cups</dd></div></dl></section>${verifiedTrust()}${company.leadership.length?`<section><h2>Leadership</h2><div class="editorial-grid">${company.leadership.map(person=>`<article><h3>${esc(person.name)}</h3><p>${esc(person.role)}</p></article>`).join('')}</div></section>`:''}${company.history.length?`<section><h2>Company story</h2>${company.history.map(x=>`<p>${esc(x)}</p>`).join('')}</section>`:''}${company.milestones.length?`<section><h2>Milestones</h2><ul>${company.milestones.map(x=>`<li>${esc(x.year)} - ${esc(x.description)}</li>`).join('')}</ul></section>`:''}<section class="values"><h2>A straightforward way to work.</h2><p>Clear specifications. Product-specific information. Agreed commercial terms. These are the principles behind the buying conversation.</p></section>`;
 if(slug==='sustainability')extra=`<section class="documentation-panel"><h2>Ask about the specific product.</h2><p>Bring your material requirements and local disposal context into the enquiry. Recycling or composting claims need evidence for the exact construction and relevant infrastructure.</p>${quote('Discuss Material Requirements','','Product enquiry')}</section>`;
 if(slug==='export')extra=`${pathwayCards()}<section class="form-section"><h2>Send your sourcing requirement.</h2>${form('Export enquiry','','export')}</section>`;
 if(slug==='resources')extra=`<section class="reference-library"><h2>Explore complete range visuals</h2><p>Browse complete compositions alongside our product-family pages.</p><label for="reference-catalogue">Choose a range<select id="reference-catalogue">${catalogueSources.map(c=>`<option value="catalogue-${c.id}">${esc(c.family)} / ${c.id}</option>`).join('')}</select></label><button class="button outline" id="open-reference-catalogue" type="button">View Complete Range ${icon()}</button></section>`+`<section class="documentation-panel"><h2>Need the current catalogue?</h2><p>Request the latest product availability and specifications directly from the team.</p>${company.catalogue?link('Download Catalogue',company.catalogue,'button'):quote('Request Catalogue','','Catalogue request')}</section>`;
 return `${pageHero('SKP / '+slug.replaceAll('-',' '),p.title,p.intro)}<section class="wrap section">${editorial(p.sections)}${extra}</section>${cta()}`;
}
export function industryPage(path){const connected=industryDetail(path);if(connected)return connected;const item=industries.find(i=>path==='/industries/'+i.slug);if(!item)return industryDiscovery();
 return `${pageHero(item.active?'MARKETS WE SERVE':'SPECIAL REQUIREMENT ENQUIRY',item.name,item.description)}<section class="wrap section"><div class="buyer-brief"><div><p class="eyebrow">THE BUYING REQUIREMENT</p><h2>Plan around your operation.</h2><p>${esc(item.detail)}</p></div><aside><h3>Include in your enquiry</h3><p>${esc(item.brief)}.</p>${quote('Discuss Your Requirement','','Industry enquiry')}</aside></div>${heading('RELEVANT RANGE','Explore the product families')}<div class="category-grid">${categories.filter(c=>!c.legacy&&item.categories.includes(c.slug)).map(categoryCard).join('')}</div></section>${cta()}`;
}
export function solutionPage(path){if(path==='/solutions')return solutionsLanding();const visual=solutionExperiences.find(s=>path==='/solutions/'+s.slug);if(visual)return visualDetail(visual,'solution');const s=solutions.find(x=>path==='/solutions/'+x.slug);return s?`${pageHero('APPLICATION SOLUTIONS',s.name,s.description)}<section class="wrap section"><div class="buyer-brief"><div><h2>Build the brief around the application.</h2><p>${esc(s.detail)}</p></div><aside><h3>Next step</h3><p>Share the format, volume and destination. Confirm suitability and current specifications with our team.</p>${quote('Discuss Your Requirement','','Product enquiry')}</aside></div><div class="category-grid">${categories.filter(c=>s.categories.includes(c.slug)).map(categoryCard).join('')}</div></section>${cta()}`:`${pageHero('APPLICATION SOLUTIONS','Foodservice starts with the application.','Explore packaging solutions for beverage, takeaway, catering, bakery, sweets and institutional requirements.')}<section class="wrap section">${applicationCards()}</section>${cta()}`;}
export const contact=contactPage;
export const rfq=()=>`${pageHero('REQUEST A QUOTE','Start with your requirement.','Tell us the product, application, estimated quantity and destination. You can leave technical fields blank if you need guidance.')}<section class="wrap section rfq-layout"><aside><h2>A useful buying brief</h2><ul class="checklist"><li>Product or service format</li><li>Intended application</li><li>Approximate quantities</li><li>Material or artwork requirements</li><li>Delivery destination</li></ul><p>Prefer to talk directly?</p><a class="contact-link" href="tel:${company.phone.replaceAll(' ','')}">${company.phone}</a><a class="contact-link" href="mailto:${company.email}">${company.email}</a></aside><div>${form()}</div></section>`;
export function legal(slug){const p=legalPages[slug];return `${pageHero('WEBSITE INFORMATION',p.title,p.intro)}<section class="wrap section legal-content">${p.sections.map(([h,t])=>`<section><h2>${esc(h)}</h2><p>${esc(t)}</p></section>`).join('')}<p>Contact: <a href="mailto:${company.email}">${company.email}</a></p></section>`;}
export const notFound=()=>`<section class="wrap section not-found"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>Let us get you to the right place.</h1><p class="lede">This page is unavailable. Explore the product range or contact the team about your requirement.</p><div class="actions">${link('Go to Homepage','/','button outline')}${link('Explore Products','/products','button')}${link('Contact Us','/contact','button outline')}</div></section>`;
