import {categories,productGroups} from '../data/products.js';
import {productMedia} from '../data/productMedia.js';
import {imageAssets} from '../image-map.js';
import {platform} from '../data/platform.js';
import {esc,link,quote,photo,breadcrumb,pageHero,icon} from './ui.js';
import {form} from './forms.js';
const ranges=productGroups.flatMap(g=>categories.filter(c=>!c.legacy&&c.group===g.id));
export function catalogueCentre(){return `${pageHero('SKP / PRODUCT CATALOGUES','A wider view of the range.','Explore tableware, packaging and material ranges. Open a complete range visual, then discuss the formats that suit your business.')}<section class="wrap section"><div class="actions">${link('Explore Products','/products','button')}${link('Request Samples','/samples','button outline')}${platform.officialCatalogues.en?link('Download Complete Catalogue',platform.officialCatalogues.en,'button outline'):''}</div>${productGroups.map(g=>`<section class="catalogue-library-group"><p class="eyebrow">${esc(g.name)}</p><div class="catalogue-library-grid">${ranges.filter(c=>c.group===g.id).map(c=>`<a class="catalogue-library-card" href="/catalogues/${c.slug}"><div>${photo(c.image,c.name)}</div><h2>${esc(c.name)}</h2><p>${esc(c.description)}</p><span class="text-link">View Range ${icon()}</span></a>`).join('')}</div></section>`).join('')}</section>`;}
export function catalogueViewer(slug){const c=ranges.find(x=>x.slug===slug);if(!c)return '';const index=ranges.indexOf(c),media=imageAssets[productMedia[c.slug]?.catalogue];return `<section class="wrap section range-viewer">${breadcrumb([{name:'Catalogues',href:'/catalogues'},{name:c.name}])}<div class="range-viewer-heading"><div><p class="eyebrow">SKP / COMPLETE RANGE</p><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p></div><div class="actions">${link('Explore Range','/products/'+c.slug,'button')}${quote('Request a Quote','','Category enquiry',c.slug)}${link('Request Samples','/samples?category='+c.slug,'button outline')}</div></div><p class="caption">Illustrative range artwork. Contact the team for current commercial specifications.</p>${media?`<figure class="complete-range-art"><img src="${media.src}" alt="${esc(c.name)} complete range artwork" width="${media.width||1536}" height="${media.height||1024}" fetchpriority="high" decoding="async"></figure>`:''}<nav class="range-viewer-nav" aria-label="Range navigation">${index>0?link('Previous Range','/catalogues/'+ranges[index-1].slug):'<span></span>'}${link('Back to Catalogues','/catalogues')}${index<ranges.length-1?link('Next Range','/catalogues/'+ranges[index+1].slug):'<span></span>'}</nav></section>`;}
export function enquiryPage(){return `${pageHero('SKP / PROCUREMENT SHORTLIST','Your Enquiry List','Build one requirement across multiple product families. Add quantities and notes, then prepare a bulk enquiry for the team.')}<section class="wrap section enquiry-workspace"><div><div class="enquiry-empty" data-enquiry-empty><h2>Your list is empty.</h2><p>Explore the range and add the product families you need.</p>${link('Explore Products','/products','button')}${link('View Catalogues','/catalogues')}</div><div data-enquiry-items></div><p class="caption" data-storage-note>Your selections are saved on this device. Contact details are not stored.</p><div class="actions">${link('Add More Products','/products','button outline')}${link('Request Samples','/samples?from=list','button outline')}</div></div><div class="enquiry-buyer"><h2>Request Bulk Quote</h2><label class="enquiry-intent">Enquiry type<select id="list-intent"><option value="Domestic bulk">Domestic bulk</option><option value="Export enquiry">Export enquiry</option></select></label><div data-multi-form>${form('Domestic bulk','','list')}</div></div></section>`;}
export function samplePage(){return `${pageHero('SKP / SAMPLE REQUIREMENTS','Discuss Sample Requirement','Select the product families you would like to evaluate. Sample availability, charges and delivery arrangements are discussed with the team.')}<section class="wrap section sample-workspace"><div><h2>Products for your sample enquiry</h2><div data-sample-items></div><label>Choose a product family<select id="sample-product"><option value="">Select a product</option></select></label><button class="button outline" type="button" id="add-sample-product">Add Product ${icon()}</button><p class="caption">A sample request does not confirm availability or free delivery.</p></div><div><h2>Your business requirement</h2><div data-sample-form>${form('Sample request','','sample')}<label>Shipping city / address<textarea name="shippingAddress" rows="3" maxlength="600" form="sample-request-form"></textarea></label><label>Courier preference / account (optional)<input name="courierPreference" maxlength="150" form="sample-request-form"></label></div></div></section>`;}
