import {imageAssets} from '../image-map.js';
import {company} from '../data/company.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon=(kind='arrow')=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">${kind==='menu'?'<path d="M4 6h16M4 12h16M4 18h16"/>':kind==='close'?'<path d="m6 6 12 12M18 6 6 18"/>':kind==='chevron'?'<path d="m6 9 6 6 6-6"/>':kind==='filter'?'<path d="M4 6h16M7 12h10M10 18h4"/>':'<path d="M6 18 18 6M6 6h12v12"/>'}</svg>`;
export const link=(text,url,cls='text-link')=>`<a class="${cls}" href="${esc(url)}">${esc(text)} ${icon()}</a>`;
export const quote=(label='Request a Quote',product='',kind='Domestic bulk',category='')=>`<button type="button" class="button" data-quote="${esc(product)}" data-kind="${esc(kind)}" data-category="${esc(category)}">${esc(label)} ${icon()}</button>`;
export const heading=(eyebrow,title,description='')=>`<div class="section-head"><div><p class="eyebrow">${esc(eyebrow)}</p><h2>${esc(title)}</h2></div>${description?`<p>${esc(description)}</p>`:''}</div>`;
export function photo(key,alt,{priority=false,sizes='(max-width:600px) 90vw, (max-width:1024px) 45vw, 30vw',cls=''}={}){
 const a=imageAssets[key];if(!a)return `<div class="photo-placeholder"><span>SKP</span><p>Product photograph on request</p></div>`;
 return `<img class="actual-product-photo ${cls}" src="${a.src}" srcset="${a.srcset}" sizes="${sizes}" alt="${esc(alt)}" width="${a.width}" height="${a.height}" loading="${priority?'eager':'lazy'}" decoding="async" ${priority?'fetchpriority="high"':''}>`;
}
export const brand=()=>`<a class="logo" href="/" aria-label="SKP - S. K. Thermoformers home"><img src="${imageAssets.logo.src}" width="249" height="89" alt="SKP"><span>S. K. THERMOFORMERS<small>FOODSERVICE DISPOSABLES</small></span></a>`;
export const pageHero=(eyebrow,title,intro)=>`<section class="page-hero wrap"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1><p class="lede">${esc(intro)}</p></section>`;
export const breadcrumb=items=>`<nav class="breadcrumb" aria-label="Breadcrumb"><ol>${[{name:'Home',href:'/'},...items].map((x,i)=>`<li>${x.href?`<a href="${x.href}">${esc(x.name)}</a>`:`<span aria-current="page">${esc(x.name)}</span>`}</li>`).join('')}</ol></nav>`;
export const cta=(title='Let us help define your requirement.',intro='Share the product, quantity and destination. Our team will discuss specifications and availability.',{product='',category=''}={})=>`<section class="enquiry-band"><div class="wrap"><div><p class="eyebrow">BUSINESS ENQUIRIES</p><h2>${esc(title)}</h2><p>${esc(intro)}</p></div><div class="actions">${quote('Request a Quote',product,'Domestic bulk',category)}${link('Contact the team','/contact','button outline')}</div></div></section>`;
export function factoryPanel(){return company.media.factory?`<figure class="factory-panel">${photo(company.media.factory,'SK Thermoformers manufacturing facility')}<figcaption>Company-approved factory photography.</figcaption></figure>`:`<div class="factory-panel neutral-process" aria-label="Paper cup specification illustration, not factory photography"><div class="technical-label">PAPER CUP / SPECIFICATION STUDY</div><svg viewBox="0 0 480 310" fill="none" aria-hidden="true"><path d="M149 75 179 247Q240 267 301 247L331 75" stroke="currentColor" stroke-width="2"/><ellipse cx="240" cy="75" rx="91" ry="23" stroke="currentColor" stroke-width="2"/><ellipse cx="240" cy="75" rx="78" ry="16" stroke="currentColor"/><path d="M365 75v172M353 75h24M353 247h24M145 278h190M145 266v24M335 266v24M130 75h-24M130 247h-24M118 75v172" stroke="currentColor" stroke-width="1"/><path d="M220 147h40M240 127v40" stroke="#c90019" stroke-width="2"/></svg><p>Capacity. Dimensions. Construction.</p><small>Neutral technical illustration; not an actual factory or product drawing.</small></div>`;}
