import {esc,link,quote,breadcrumb,heading} from './ui.js';
import {categories} from '../data/products.js';
import {categoryCard} from './catalogue.js';
import {form} from './forms.js';
// Native-size contextual backgrounds today; full-cover mode when approved large imagery arrives.
const mediaStyle=(m,position)=>`--detail-image:url('${esc(m.src)}');--detail-position:${esc(position)};--detail-width:${m.width}px;--detail-ratio:${m.width/m.height}`;
export function visualDetail(item,type){
 const industry=type==='industry',group=industry?'Industries':'Solutions',root=industry?'/industries':'/solutions',contextKey=industry?'industry':'application';
 const contextButton=(label='Discuss Your Requirement')=>quote(label,'','Domestic bulk').replace('data-quote=',`data-${contextKey}="${esc(item.ctaContext)}" data-quote=`);
 const hero=item.heroImage||item.cardImage,band=item.backgroundImage||item.cardImage;
 const mode=m=>m.width>=1600?'detail-cover':'detail-native';
 const contextHref='/contact?'+contextKey+'='+encodeURIComponent(item.ctaContext);
 const contextualForm=form('Domestic bulk','','detail-'+type+'-'+item.slug).replace(`name="${contextKey}" value=""`,`name="${contextKey}" value="${esc(item.ctaContext)}"`).replace('<strong data-industry-name></strong>',`<strong data-industry-name>${esc(item.ctaContext)}</strong>`).replace('class="rfq-industry-context" hidden','class="rfq-industry-context"');
 return `<article class="visual-detail visual-detail-${type}" data-visual-source="${esc(item.cardImage.src)}"><section class="detail-atmosphere detail-hero ${mode(hero)}" style="${mediaStyle(hero,item.heroPosition)}"><div class="detail-fade" aria-hidden="true"></div><div class="wrap detail-content"><div class="detail-hero-copy">${breadcrumb([{name:group,href:root},{name:item.title}])}<p class="eyebrow">${industry?'INDUSTRY SOLUTIONS':'APPLICATION SOLUTIONS'}</p><h1>${esc(item.title)}</h1><p class="lede">${esc(item.shortDescription)}</p><div class="actions">${link('Explore Relevant Products','#relevant-products','button')}${contextButton()}</div></div></div></section><section class="wrap section detail-brief"><div><p class="eyebrow">${industry?'INDUSTRY REQUIREMENTS':'YOUR APPLICATION'}</p><h2>${industry?'Plan around your operation.':'Build the brief around the application.'}</h2><p>${esc(item.requirement)}</p></div><aside><h3>Include in your enquiry</h3><p>${esc(item.brief)}</p></aside></section><section class="muted-surface section" id="relevant-products"><div class="wrap">${heading('RELEVANT PRODUCT FAMILIES','Explore formats for your business.')}<div class="category-grid">${categories.filter(c=>!c.legacy&&item.productCategories.includes(c.slug)).map(c=>categoryCard(c).replaceAll('href="/products/'+c.slug+'"','href="/products/'+c.slug+'?'+contextKey+'='+encodeURIComponent(item.ctaContext)+'"')).join('')}</div></div></section><section class="detail-atmosphere detail-visual-band ${mode(band)}" style="${mediaStyle(band,item.backgroundPosition||'right center')}"><div class="detail-fade" aria-hidden="true"></div><div class="wrap detail-content"><div class="detail-enquiry-panel"><p class="eyebrow">BULK & CUSTOM REQUIREMENTS</p><h2>${esc(item.applicationTitle||item.title)}</h2><p>Tell us what you are serving, packing or distributing. Share your quantities and the details that matter to your operation.</p><div class="actions">${contextButton('Request a Quote')}${link('Contact the team',contextHref,'button outline')}</div></div></div></section><section class="wrap detail-enquiry industry-enquiry" id="industry-enquiry"><div><p class="eyebrow">SEND YOUR REQUIREMENT</p><h2>Start the product discussion.</h2><p>Include your application, quantities and delivery destination.</p></div><div>${contextualForm}</div></section></article>`;
}
