import {chromium} from '@playwright/test';import {writeFile,mkdir} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const reports=[];
for(const route of ['/','/products','/products/paper-cups','/manufacturing','/contact','/rfq']){
 await page.goto('http://localhost:3001'+route);const contrast=await page.evaluate(()=>{
  const parse=s=>{const n=s.match(/[\d.]+/g)?.map(Number)||[];return n.length>=3?n:null;};
  const lum=c=>{const a=c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return a[0]*.2126+a[1]*.7152+a[2]*.0722};let failures=[];
  for(const e of document.querySelectorAll('body *')){if(e.closest('dialog:not([open]),[hidden],script,style,svg')||!e.getClientRects().length||![...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()))continue;const c=getComputedStyle(e),fg=parse(c.color);let parent=e,bg=null;while(parent){const candidate=parse(getComputedStyle(parent).backgroundColor);if(candidate&&candidate[3]!==0){bg=candidate;break;}parent=parent.parentElement;}if(!fg||!bg||bg[3]&&bg[3]<1)continue;const ratio=(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05);const large=parseFloat(c.fontSize)>=24||(parseFloat(c.fontSize)>=18.66&&parseInt(c.fontWeight)>=700);if(ratio<(large?3:4.5))failures.push({text:e.textContent.trim().slice(0,70),ratio:Math.round(ratio*100)/100,fontSize:c.fontSize});}
 return failures;
 });reports.push({route,contrastFailures:contrast});
}
await page.goto('http://localhost:3001/');await page.keyboard.press('Tab');const skip=await page.evaluate(()=>document.activeElement.textContent);if(skip!=='Skip to content')throw Error('Skip link');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.activeElement.id==='main');
await page.emulateMedia({reducedMotion:'reduce'});if(await page.evaluate(()=>getComputedStyle(document.querySelector('.button')).transitionDuration)!=='0s')throw Error('Reduced motion');
const timings=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation')[0].toJSON(),resources:performance.getEntriesByType('resource').map(r=>({name:r.name,transferSize:r.transferSize,encodedBodySize:r.encodedBodySize})),fonts:document.fonts.size}));
await mkdir('docs/qa/refinement',{recursive:true});await writeFile('docs/qa/refinement/accessibility-performance.json',JSON.stringify({reports,skipLink:'passed',reducedMotion:'passed',localTimings:timings,notes:'Contrast check uses computed solid backgrounds; this is a focused accessibility review, not a WCAG certification or field Core Web Vitals measurement.'},null,2));await browser.close();if(reports.some(r=>r.contrastFailures.length))throw Error(JSON.stringify(reports));console.log('Computed text contrast, keyboard skip link and reduced-motion checks passed.');
