import {chromium} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import {routes,products,categories,company} from '../src/data.js';import {imageAssets} from '../src/image-map.js';import {render,metadata} from '../src/render.js';import assert from 'node:assert/strict';
const root='docs/qa/refinement';await mkdir(root,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];let expected404=false;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!expected404)errors.push(m.text())});
const result={routes:routes.length,viewports:[360,390,430,768,1024,1440],pages:[],overflow:[],missingImages:[],consoleErrors:errors,checks:[]};const titles=new Set(),descs=new Set();
for(const [i,route] of routes.entries()){
 const res=await page.goto('http://localhost:3001'+route);assert.equal(res.status(),200,route);await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode()})));
 const title=await page.title();assert(!titles.has(title),'Duplicate title '+route);titles.add(title);const desc=await page.locator('meta[name=description]').getAttribute('content');assert(!descs.has(desc),'Duplicate description '+route);descs.add(desc);
 assert.equal(await page.locator('main h1').count(),1,'H1 '+route);assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),company.url+(route==='/'?'':route));
 const html=await page.content();assert(!/[\uFFFD\u00c2\u00c3]|\u00e2\u20ac/.test(html),'Malformed text '+route);
 const links=await page.locator('a[href^="/"]').evaluateAll(a=>a.map(x=>new URL(x.href).pathname));for(const href of links)assert(routes.includes(href)||href.startsWith('/assets/'),'Internal link '+href+' on '+route);
 const unlabeled=await page.locator('input:not([type=hidden]),select,textarea').evaluateAll(a=>a.filter(e=>!e.closest('label')&&!e.labels?.length&&!e.getAttribute('aria-label')).map(e=>e.name));assert.equal(unlabeled.length,0,'Missing labels '+route);
 const broken=await page.locator('img').evaluateAll(a=>a.filter(i=>!i.naturalWidth).map(i=>i.src));assert.equal(broken.length,0,'Images '+route);
 result.pages.push({route,title,description:desc,status:200});
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:`${root}/route-${i}.png`,fullPage:true});
}
console.log('Route audit passed: '+routes.length+' routes, metadata, links, labels and images.');
for(const width of result.viewports){await page.setViewportSize({width,height:900});for(const route of routes){await page.goto('http://localhost:3001'+route);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))result.overflow.push({width,route});}console.log('Responsive check complete: '+width+'px');}
assert.equal(result.overflow.length,0,JSON.stringify(result.overflow));
await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:3001/products');await page.locator('#search').fill('printed');assert.equal(await page.locator('.catalog-products .product-card:visible').count(),1);await page.locator('#reset-filters').click();await page.locator('#material').selectOption('Plastic');assert.equal(await page.locator('.catalog-products .product-card:visible').count(),3);await page.locator('#reset-filters').click();await page.locator('#custom').selectOption('true');assert.equal(await page.locator('.catalog-products .product-card:visible').count(),3);await page.locator('#search').fill('no matching format');assert(await page.locator('#no-results').isVisible());
await page.goto('http://localhost:3001/products/custom-products');assert.equal(await page.locator('.catalog-products .product-card:visible').count(),3);await page.locator('#category').selectOption('bowls');await page.waitForURL('**/products/bowls');assert.equal(await page.locator('.catalog-products .product-card:visible').count(),2);
result.checks.push('Search, material, printing, empty states and cross-category navigation');
for(const p of products){await page.goto('http://localhost:3001/products/'+p.slug);const btn=page.locator('.product-summary [data-quote]').first();await btn.click();assert.equal(await page.locator('#rfq-modal [name=product]').inputValue(),p.slug);assert.equal(await page.locator('#rfq-modal [name=category]').inputValue(),p.category);await page.keyboard.press('Escape');assert(!await page.locator('#rfq-modal').isVisible());assert(await btn.evaluate(e=>e===document.activeElement));}
await page.goto('http://localhost:3001/products/bowls');await page.getByRole('button',{name:'Discuss this range',exact:true}).click();assert.equal(await page.locator('#rfq-modal [name=category]').inputValue(),'bowls');await page.keyboard.press('Escape');result.checks.push('All product RFQs and category context, Escape and restored focus');
await page.goto('http://localhost:3001/rfq?kind=Export%20enquiry&product=paper-cups');const f=page.locator('main form');assert.equal(await f.locator('[name=product]').inputValue(),'paper-cups');assert.equal(await f.locator('[name=pathway]').inputValue(),'Export enquiry');assert.equal(await f.locator('[name=quantity]').getAttribute('required'),null);await f.locator('[name=name]').fill('QA Buyer');await f.locator('[name=email]').fill('qa@example.com');await f.locator('[name=consent]').check();await f.getByRole('button',{name:'Prepare Email Enquiry',exact:true}).click();assert(await f.locator('.email-result').isVisible());assert((await f.locator('[data-email-link]').getAttribute('href')).startsWith('mailto:'+company.email));assert((await f.locator('.form-status').textContent()).includes('Nothing has been sent'));const download=page.waitForEvent('download');await f.getByRole('button',{name:'Download Enquiry Text'}).click();assert.equal((await download).suggestedFilename(),'skp-enquiry.txt');
await f.locator('[name=artwork]').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('QA')});await f.getByRole('button',{name:'Prepare Email Enquiry',exact:true}).click();assert((await f.locator('.form-status').textContent()).includes('Select a PDF'));result.checks.push('RFQ minimal fields, export prefill, email draft, download and attachment validation; no message sent');
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:3001/products');await page.getByRole('button',{name:'Search & Filters'}).click();assert(await page.locator('#filter-panel').isVisible());assert.equal(await page.locator('#filter-panel').getAttribute('aria-modal'),'true');await page.locator('#search').fill('plastic');await page.keyboard.press('Escape');assert(!await page.locator('#filter-panel').isVisible());assert(await page.locator('.filter-toggle').evaluate(e=>e===document.activeElement));await page.getByRole('button',{name:'Open navigation'}).click();assert(await page.locator('#mobile-nav').isVisible());await page.keyboard.press('Escape');assert(!await page.locator('#mobile-nav').isVisible());result.checks.push('Mobile filter drawer, navigation, keyboard dismissal and focus');
await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:3001/');await page.getByRole('button',{name:'Products',exact:true}).click();assert(await page.locator('#product-menu').isVisible());assert.equal(await page.locator('#product-menu .mega-links a').count(),7);await page.keyboard.press('Escape');assert(!await page.locator('#product-menu').isVisible());await page.evaluate(()=>scrollTo(0,600));await page.waitForFunction(()=>document.querySelector('header').classList.contains('scrolled'));result.checks.push('Desktop mega menu and sticky header');
expected404=true;const missing=await page.goto('http://localhost:3001/does-not-exist');assert.equal(missing.status(),404);assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,follow');assert(await page.getByRole('heading',{name:'Let us get you to the right place.'}).isVisible());result.checks.push('404 HTTP status, recovery links and noindex');expected404=false;
for(const width of [390,1440]){await page.setViewportSize({width,height:1000});for(const [name,route] of Object.entries({home:'/',catalogue:'/products',product:'/products/paper-cups',pending:'/products/food-containers',manufacturing:'/manufacturing',contact:'/contact',rfq:'/rfq',sustainability:'/sustainability'})){await page.goto('http://localhost:3001'+route);await page.locator('img').evaluateAll(a=>Promise.all(a.map(i=>{i.loading='eager';return i.decode()})));await page.screenshot({path:`${root}/${name}-${width}.png`,fullPage:true});if(name==='home')await page.screenshot({path:`${root}/hero-${width}.png`});}}
assert.equal(errors.length,0,errors.join('\n'));await writeFile(root+'/results.json',JSON.stringify(result,null,2));await browser.close();console.log('Full browser QA passed.');
