import {canShowSpecifications} from '../src/data/productPresentation.js';
import {submitEnquiry} from '../src/enquiry.js';
test('range images never publish SKU specifications or automatic capacity prefill',()=>{for(const p of products){assert(['verified','range-level','pending'].includes(p.contentState));if(!canShowSpecifications(p)){assert(!render('/products/'+p.slug).includes('<dl class="specs">'),p.slug);assert(!metadata('/products/'+p.slug).schema.some(s=>s['@type']==='Product'));}if(p.image)assert(imageAssets[p.image]);}const tea=products.find(p=>p.slug==='100ml-tea-cup');assert.equal(tea.historicalData.capacity,'100 ml');assert.equal(tea.image,null);assert.equal(tea.name,'Tea cup range');assert(!render('/products/100ml-tea-cup').includes('100 ml'));assert(!render('/products').includes('id="size"'));assert(!render('/products').includes('class="image-label"'));});
test('enquiry adapter rejects unconfirmed delivery and does not send fallback',async()=>{let calls=0;const payload=new FormData();const result=await submitEnquiry(payload,{email:'test@example.com',subject:'Product family',draft:'Requirements',transport:()=>{calls++;}});assert.equal(result.mode,'email');assert.equal(calls,0);await assert.rejects(submitEnquiry(payload,{endpoint:'/api/enquiry',transport:async()=>({ok:true,json:async()=>({success:false})})}));assert.equal((await submitEnquiry(payload,{endpoint:'/api/enquiry',transport:async()=>({ok:true,json:async()=>({success:true})})})).mode,'submitted');});
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,stat} from 'node:fs/promises';import {render,metadata} from '../src/render.js';import {routes,products,company} from '../src/data.js';import {productsForCategory,categories} from '../src/data/products.js';
import {catalogueSources,visualGroups,productMedia} from '../src/data/productMedia.js';import {imageAssets} from '../src/image-map.js';import {exportData} from '../src/data/export.js';

test('visual provenance and export facts stay distinct from product evidence',async()=>{assert.equal(catalogueSources.length,28);for(const g of visualGroups){const a=imageAssets[g.id];assert(a.sourceCatalogue);assert.equal(a.status,'unverified');assert.equal(a.width,a.crop.width);assert.equal(a.height,a.crop.height);await stat('src/assets/skp-products/'+a.source);await stat('public'+a.src);}for(const c of categories.filter(c=>!c.legacy)){assert(productMedia[c.slug]);assert(imageAssets[c.media.catalogue]);assert(productsForCategory(c).length||products.some(p=>p.category===c.slug));}assert(exportData.documents.every(d=>!d.verified&&d.document===null));assert(Object.values(exportData.packing).every(v=>v===null));assert(Object.values(exportData.commercial).every(v=>v===null));const html=render('/export');assert(!html.includes('countries served'));assert(!html.includes('Download Catalogue'));assert(html.includes('name="destination"'));assert(html.includes('name="country" autocomplete="country-name" maxlength="100" required'));});
test('all routes have unique metadata, one main heading and valid internal links',()=>{const titles=new Set(),descs=new Set();assert.equal(new Set(routes).size,routes.length);for(const route of routes){const html=render(route),m=metadata(route);assert(!titles.has(m.title),route);assert(!descs.has(m.description),route);titles.add(m.title);descs.add(m.description);assert.equal((html.match(/<h1[ >]/g)||[]).length,1,route);assert(html.includes('<main id="main"'));assert(html.includes(`rel="canonical" href="${company.url}${route==='/'?'':route}"`));assert(!html.includes('undefined'));for(const match of html.matchAll(/href="(\/[^"?#]*)/g))assert(routes.includes(match[1])||match[1].startsWith('/assets/')||match[1].startsWith('/src/'),`Broken link ${match[1]} on ${route}`);}});
test('pending products do not get confirmed Product schema or invented specifications',()=>{for(const p of products){const html=render('/products/'+p.slug);assert(html.includes(`data-quote="${p.slug}"`));assert(!html.includes('Add to Cart'));const schema=metadata('/products/'+p.slug).schema;assert.equal(schema.some(x=>x['@type']==='Product'),canShowSpecifications(p));assert(!schema.some(x=>x.offers||x.aggregateRating||x.review));if(p.referenceOnly){assert.equal(p.material,null);assert.equal(p.capacity,null);assert.equal(p.moq,null);assert(!html.includes('<dl class="specs">'));}}assert.equal(company.certifications.length,0);assert.equal(company.metrics.length,0);assert.equal(company.whatsapp,null);});
test('custom category is populated and no null-material match creates unrelated products',()=>{const c=categories.find(c=>c.slug==='custom-products');const range=productsForCategory(c);assert(range.length>0);assert(range.every(p=>p.customPrint===true));const cutlery=products.find(p=>p.slug==='disposable-spoons-forks');assert(!render('/products/'+cutlery.slug).includes('href="/products/trays-enquiry"'));});
test('RFQ is honest and requires only name, email and consent',()=>{const html=render('/rfq');assert(html.includes('Continue in your email app to send this enquiry.'));assert(html.includes('name="consent" required'));assert(html.includes('type="email"'));for(const name of ['quantity','phone','city','country','company'])assert(!new RegExp(`name="${name}"[^>]*required`).test(html));assert(!html.includes('Private label</option>'));});
test('missing routes have noindex, no canonical and recovery navigation',()=>{const html=render('/missing');assert(html.includes('name="robots" content="noindex,follow"'));assert(!html.includes('rel="canonical"'));assert(html.includes('href="/products"'));assert(html.includes('href="/contact"'));});
test('production excludes reference originals and has real social image and matching sitemap',async()=>{const sitemap=await readFile('dist/sitemap.xml','utf8');for(const r of routes)assert(sitemap.includes(company.url+(r==='/'?'':r)));assert((await stat('dist/assets/social.jpg')).size>0);await assert.rejects(stat('dist/src/assets/skp-products'));await assert.rejects(stat('dist/assets/archive'));await assert.rejects(stat('dist/assets/library'));for(const route of routes){const html=await readFile((route==='/'?'dist':'dist'+route)+'/index.html','utf8');for(const [,src] of html.matchAll(/(?:src|href)="(\/(?:assets|src)\/[^"?#]+)"/g))await stat('dist'+src);}});

test('Vercel configuration parses without a BOM and uses the static output',async()=>{const config=JSON.parse(await readFile('vercel.json','utf8'));assert.equal(config.outputDirectory,'dist');assert.equal(config.buildCommand,'npm run build');assert.equal(config.cleanUrls,true);});

import {siteMedia} from '../src/data/siteMedia.js';
test('representative visuals are route-scoped and never become product evidence',async()=>{const mapping={manufacturing:'manufacturing',quality:'quality','custom-solutions':'customPrinting',industries:'foodservice',export:'export'};for(const [route,key] of Object.entries(mapping)){const html=render('/'+route);assert(html.includes('/site-media/'+key+'-'));assert(html.includes('Representative visual'));assert(!html.includes('background-attachment: fixed'));assert.equal(siteMedia[key].status,'representative');await stat('public'+siteMedia[key].src);}assert(!render('/products').includes('/site-media/'));assert(!render('/quality').includes('starts&lt;br&gt;'));assert(render('/rfq').includes('form-optional'));assert(render('/export').includes('name="destination"'));assert(!render('/').includes('/site-media/manufacturing-'));});
