import {company,products} from './data.js';
const modal=document.querySelector('#rfq-modal');
const closeMenus=()=>document.querySelectorAll('.nav-button').forEach(b=>{b.setAttribute('aria-expanded','false');document.getElementById(b.getAttribute('aria-controls')).hidden=true;});
document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')==='true';closeMenus();b.setAttribute('aria-expanded',String(!open));document.getElementById(b.getAttribute('aria-controls')).hidden=open;}));
document.addEventListener('click',e=>{if(!e.target.closest('.mega-container,.more-container'))closeMenus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenus();const b=document.querySelector('#mobile-toggle');b.setAttribute('aria-expanded','false');document.querySelector('#mobile-nav').hidden=true;}});
document.querySelector('#mobile-toggle')?.addEventListener('click',e=>{let b=e.currentTarget;let open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));b.setAttribute('aria-label',open?'Open navigation':'Close navigation');document.querySelector('#mobile-nav').hidden=open;});
document.querySelectorAll('[data-quote]').forEach(b=>b.addEventListener('click',()=>{const f=modal.querySelector('form');f.reset();f.elements.product.value=b.dataset.quote||'';const p=products.find(p=>p.slug===b.dataset.quote);if(p){f.elements.category.value=p.category;f.elements.size.value=p.sizes.join(', ');}f.elements.enquiryType.value=b.dataset.kind;f.elements.quantity.required=!['Catalogue request','General enquiry','Product enquiry','Specification request'].includes(b.dataset.kind);modal.querySelector('#rfq-title').textContent=p?`Enquire about ${p.name}`:b.dataset.kind;f.querySelector('.form-status').textContent='';f.querySelector('.email-result').hidden=true;modal.showModal();document.body.classList.add('modal-open');}));
modal?.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal?.addEventListener('close',()=>document.body.classList.remove('modal-open'));modal?.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
document.querySelectorAll('[data-lead-form]').forEach(f=>{let draft='';const status=f.querySelector('.form-status');f.elements.quantity.required=!['Catalogue request','General enquiry','Product enquiry','Specification request'].includes(f.elements.enquiryType.value);f.addEventListener('input',()=>{f.querySelector('.email-result').hidden=true;status.textContent='';});f.elements.product.addEventListener('change',()=>{const p=products.find(p=>p.slug===f.elements.product.value);if(p){f.elements.category.value=p.category;f.elements.size.value=p.sizes.join(', ');}});f.addEventListener('submit',async e=>{e.preventDefault();if(!f.reportValidity())return;if(f.elements.website.value)return;const file=f.elements.artwork.files[0];if(file&&(file.size>5*1024*1024||! /\.(pdf|png|jpe?g|svg)$/i.test(file.name))){status.textContent='Please select a supported file smaller than 5 MB.';return;}const data=new FormData(f);const product=products.find(p=>p.slug===data.get('product'));const subject=`SK ${data.get('enquiryType')} — ${product?.name||data.get('company')}`;draft=[subject,...Array.from(data.entries()).filter(([k])=>!['website','artwork','consent'].includes(k)).map(([k,v])=>`${k}: ${k==='product'?(product?.name||'Other / help me choose'):v}`),file?`Artwork: ${file.name} (attach manually)`:''].join('\n');if(!company.leadEndpoint){f.querySelector('[data-email-link]').href=`mailto:${company.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(draft)}`;f.querySelector('.email-result').hidden=false;status.textContent='Email draft prepared. Your enquiry has not been sent.';return;}const submit=f.querySelector('[type=submit]');submit.disabled=true;status.textContent='Sending your enquiry…';try{const res=await fetch(company.leadEndpoint,{method:'POST',body:data});if(!res.ok)throw Error('Submission failed');const result=await res.json();if(result.success!==true)throw Error('Unconfirmed submission');status.textContent='Your enquiry was received.';f.reset();}catch{status.textContent='We could not confirm delivery. Please contact the team by email or phone.';}finally{submit.disabled=false;}});f.querySelector('[data-download-enquiry]')?.addEventListener('click',()=>{const u=URL.createObjectURL(new Blob([draft],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='sk-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});});
const q=new URLSearchParams(location.search);if(location.pathname==='/rfq'){const f=document.querySelector('main form');if(q.get('kind')){f.elements.enquiryType.value=q.get('kind');f.elements.quantity.required=q.get('kind')!=='Catalogue request';}}
const filters=['search','category','material','application','size'].map(id=>document.getElementById(id));if(filters[0]){const update=()=>{let count=0;const [query,cat,mat,app,size]=filters.map(f=>f.value.toLowerCase().trim());document.querySelectorAll('.catalog-products .product-card').forEach(card=>{let matches=query.split(/\s+/).every(term=>card.dataset.name.includes(term))&&(!cat||card.dataset.category===cat)&&(!mat||card.dataset.material.toLowerCase()===mat)&&(!app||card.dataset.application.toLowerCase()===app)&&(!size||card.dataset.size.toLowerCase().includes(size));card.hidden=!matches;if(matches)count++;});document.getElementById('result-count').textContent=`${count} ${count===1?'product':'products'}`;document.getElementById('no-results').hidden=count>0;};filters.forEach(f=>f.addEventListener('input',update));document.getElementById('reset-filters').addEventListener('click',()=>{filters.forEach(f=>f.value='');update();});if(q.get('q'))filters[0].value=q.get('q');update();}
