export const supportedLanguages=['en','hi'];
export const languagePath=(path,language)=>language==='hi'?'/hi'+(path==='/'?'':path):path;
export const basePath=path=>path==='/hi'?'/':path.startsWith('/hi/')?path.slice(3):path;
export const routeLanguage=path=>path==='/hi'||path.startsWith('/hi/')?'hi':'en';
// Lazy-loaded Hindi vocabulary keeps the English entry bundle small.
export async function initLanguage(){let translate=value=>value;let loaded=false;const load=async()=>{if(!loaded){translate=(await import('./locales/hi.js')).translate;loaded=true;}};const originals=new WeakMap(),attributes=new WeakMap();let language=routeLanguage(location.pathname);let applying=false;if(language==='hi')await load();
 const convert=value=>language==='hi'?translate(value):value;
 function apply(root=document.body){if(applying)return;applying=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode;if(node.parentElement?.closest('script,style,textarea,[data-user-content]'))continue;let original=originals.get(node);if(!original){const marker=node.previousSibling;original=marker?.nodeType===8&&marker.data.startsWith('i18n:')?(node.textContent.match(/^\s*/)?.[0]||'')+decodeURIComponent(marker.data.slice(5))+(node.textContent.match(/\s*$/)?.[0]||''):node.textContent;originals.set(node,original);}const next=original.replace(/\S[\s\S]*\S|\S/,m=>convert(m));if(node.textContent!==next)node.textContent=next;}
 for(const el of root.querySelectorAll('[placeholder],[aria-label],[alt],[title]')){let entry=attributes.get(el);if(!entry){const source=el.dataset.i18nAttrs?JSON.parse(el.dataset.i18nAttrs):Object.fromEntries(['placeholder','aria-label','alt','title'].filter(a=>el.hasAttribute(a)).map(a=>[a,el.getAttribute(a)]));entry={source,last:Object.fromEntries(Object.keys(source).map(a=>[a,el.getAttribute(a)]))};attributes.set(el,entry);}for(const name of Object.keys(entry.source)){const current=el.getAttribute(name);if(current!==entry.last[name])entry.source[name]=current;const next=convert(entry.source[name]);if(current!==next)el.setAttribute(name,next);entry.last[name]=next;}}
 for(const anchor of root.querySelectorAll('a[href]')){const href=anchor.getAttribute('href');if(href.startsWith('/')&&!href.startsWith('/assets/')&&!href.startsWith('/src/')){const original=basePath(href);const next=languagePath(original==='/'?'/':original,language);if(href!==next)anchor.setAttribute('href',next);}}
 document.documentElement.lang=language;document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===language)));applying=false;}
 async function switchLanguage(next,{remember=true}={}){if(next==='hi')await load();language=next;if(remember)try{localStorage.setItem('skp-language',next);}catch{}const pathname=languagePath(basePath(location.pathname),next);history.replaceState(history.state,'',pathname+location.search+location.hash);apply();for(const element of document.head.querySelectorAll('[data-i18n-head]')){const value=convert(element.dataset.i18nHead);if(element.tagName==='TITLE')element.textContent=value;else element.setAttribute('content',value);}const canonical=document.querySelector('link[rel=canonical]');if(canonical){const url=new URL(canonical.href);url.pathname=pathname;canonical.href=url.href;document.querySelector('meta[property="og:url"]').content=url.href;}document.querySelector('meta[property="og:locale"]').content=next==='hi'?'hi_IN':'en_IN';document.dispatchEvent(new CustomEvent('skp:language',{detail:next}));}
 document.querySelectorAll('option:not([value])').forEach(option=>option.value=option.textContent);
 document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>switchLanguage(button.dataset.language)));
 document.addEventListener('skp:content',()=>apply());const observer=new MutationObserver(()=>apply());observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','placeholder','alt','title']});
 document.addEventListener('invalid',event=>{const input=event.target;if(!input.setCustomValidity)return;input.setCustomValidity('');const message=input.validity.valueMissing?'Please complete this required field.':input.validity.typeMismatch?'Enter a valid email address.':input.validity.patternMismatch?'Enter a valid phone number.':'Check this field and try again.';if(language==='hi')input.setCustomValidity(translate(message));},true);
 document.addEventListener('input',event=>event.target.setCustomValidity?.(''));document.addEventListener('change',event=>event.target.setCustomValidity?.(''));
 document.addEventListener('skp:language',()=>document.querySelectorAll('input,select,textarea').forEach(el=>el.setCustomValidity?.('')));
 // Explicit /hi URLs win; a remembered preference only changes a fresh English entry.
 let preference;try{preference=localStorage.getItem('skp-language');}catch{}if(language==='en'&&preference==='hi')await switchLanguage('hi',{remember:false});else if(language==='hi')await switchLanguage('hi',{remember:false});else apply();
 return {translate:convert,apply,switchLanguage};
}
