// Generated by scripts/prepare-skp-images.mjs. Replace asset records centrally.
export const imageAssets = {
  "paper-cups": {
    "src": "/assets/skp/paper-cups-373.webp",
    "srcset": "/assets/skp/paper-cups-240.webp 240w, /assets/skp/paper-cups-373.webp 373w",
    "width": 373,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 8,
      "top": 337,
      "width": 373,
      "height": 173
    }
  },
  "plastic-cups": {
    "src": "/assets/skp/plastic-cups-370.webp",
    "srcset": "/assets/skp/plastic-cups-240.webp 240w, /assets/skp/plastic-cups-370.webp 370w",
    "width": 370,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 393,
      "top": 337,
      "width": 370,
      "height": 173
    }
  },
  "plates": {
    "src": "/assets/skp/plates-369.webp",
    "srcset": "/assets/skp/plates-240.webp 240w, /assets/skp/plates-369.webp 369w",
    "width": 369,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 337,
      "width": 369,
      "height": 173
    }
  },
  "bowls": {
    "src": "/assets/skp/bowls-372.webp",
    "srcset": "/assets/skp/bowls-240.webp 240w, /assets/skp/bowls-372.webp 372w",
    "width": 372,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 1157,
      "top": 337,
      "width": 372,
      "height": 173
    }
  },
  "cutlery": {
    "src": "/assets/skp/cutlery-373.webp",
    "srcset": "/assets/skp/cutlery-240.webp 240w, /assets/skp/cutlery-373.webp 373w",
    "width": 373,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 8,
      "top": 569,
      "width": 373,
      "height": 153
    }
  },
  "food-containers": {
    "src": "/assets/skp/food-containers-370.webp",
    "srcset": "/assets/skp/food-containers-240.webp 240w, /assets/skp/food-containers-370.webp 370w",
    "width": 370,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 393,
      "top": 569,
      "width": 370,
      "height": 153
    }
  },
  "paper-products": {
    "src": "/assets/skp/paper-products-369.webp",
    "srcset": "/assets/skp/paper-products-240.webp 240w, /assets/skp/paper-products-369.webp 369w",
    "width": 369,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 569,
      "width": 369,
      "height": 153
    }
  },
  "thermoformed": {
    "src": "/assets/skp/thermoformed-372.webp",
    "srcset": "/assets/skp/thermoformed-240.webp 240w, /assets/skp/thermoformed-372.webp 372w",
    "width": 372,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 1157,
      "top": 569,
      "width": 372,
      "height": 153
    }
  },
  "custom-printed": {
    "src": "/assets/skp/custom-printed-373.webp",
    "srcset": "/assets/skp/custom-printed-240.webp 240w, /assets/skp/custom-printed-373.webp 373w",
    "width": 373,
    "height": 123,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 8,
      "top": 780,
      "width": 373,
      "height": 123
    }
  },
  "specialty": {
    "src": "/assets/skp/specialty-369.webp",
    "srcset": "/assets/skp/specialty-240.webp 240w, /assets/skp/specialty-369.webp 369w",
    "width": 369,
    "height": 123,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 780,
      "width": 369,
      "height": 123
    }
  },
  "trays": {
    "src": "/assets/skp/trays-184.webp",
    "srcset": "/assets/skp/trays-184.webp 184w, /assets/skp/trays-184.webp 184w",
    "width": 184,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 762,
      "top": 714,
      "width": 184,
      "height": 174
    }
  },
  "clamshell": {
    "src": "/assets/skp/clamshell-180.webp",
    "srcset": "/assets/skp/clamshell-180.webp 180w, /assets/skp/clamshell-180.webp 180w",
    "width": 180,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 571,
      "top": 714,
      "width": 180,
      "height": 174
    }
  },
  "portion-cups": {
    "src": "/assets/skp/portion-cups-205.webp",
    "srcset": "/assets/skp/portion-cups-205.webp 205w, /assets/skp/portion-cups-205.webp 205w",
    "width": 205,
    "height": 176,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 1323,
      "top": 472,
      "width": 205,
      "height": 176
    }
  },
  "dessert-cups": {
    "src": "/assets/skp/dessert-cups-188.webp",
    "srcset": "/assets/skp/dessert-cups-188.webp 188w, /assets/skp/dessert-cups-188.webp 188w",
    "width": 188,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 8,
      "top": 714,
      "width": 188,
      "height": 174
    }
  },
  "takeaway": {
    "src": "/assets/skp/takeaway-185.webp",
    "srcset": "/assets/skp/takeaway-185.webp 185w, /assets/skp/takeaway-185.webp 185w",
    "width": 185,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 956,
      "top": 714,
      "width": 185,
      "height": 174
    }
  },
  "hero": {
    "src": "/assets/skp/hero-1101.webp",
    "srcset": "/assets/skp/hero-550.webp 550w, /assets/skp/hero-1101.webp 1101w",
    "width": 1101,
    "height": 327,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 435,
      "top": 0,
      "width": 1101,
      "height": 327
    }
  },
  "logo": {
    "src": "/assets/skp/logo-249.webp",
    "srcset": "/assets/skp/logo-249.webp 249w",
    "width": 249,
    "height": 89,
    "source": "ChatGPT Image Oct 1, 2026, 08_33_22 PM.png",
    "crop": {
      "left": 43,
      "top": 31,
      "width": 249,
      "height": 89
    }
  }
};
export const categoryImages = {'cups-glasses':'paper-cups',plates:'plates','plates-trays':'plates',trays:'trays',bowls:'bowls',cutlery:'cutlery','food-containers':'food-containers','clamshell-containers':'clamshell','portion-sauce-cups':'portion-cups','dessert-ice-cream-cups':'dessert-cups','takeaway-packaging':'takeaway','thermoformed-products':'thermoformed','paper-products':'paper-products','custom-products':'custom-printed','specialty-products':'specialty'};
export const productImages = {'paper-cups':'paper-cups','printed-paper-cups':'custom-printed','100ml-tea-cup':'paper-cups','disposable-juice-glass':'plastic-cups','water-plastic-glass':'plastic-cups','plastic-cups':'plastic-cups','paper-bowls':'bowls','plastic-bowls':'bowls','paper-plates':'plates','disposable-spoons-forks':'cutlery','table-tissues':'paper-products'};
export const heroImages={home:'hero',custom:'custom-printed'};
export const industryImages={};
