// Generated by scripts/prepare-product-library.mjs. Originals and crop provenance are retained.
export const imageAssets={
  "paper-cups": {
    "src": "/assets/skp/paper-cups-373.webp",
    "srcset": "/assets/skp/paper-cups-240.webp 240w, /assets/skp/paper-cups-373.webp 373w",
    "width": 373,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 8,
      "top": 337,
      "width": 373,
      "height": 173
    }
  },
  "plastic-cups": {
    "src": "/assets/skp/plastic-cups-370.webp",
    "srcset": "/assets/skp/plastic-cups-240.webp 240w, /assets/skp/plastic-cups-370.webp 370w",
    "width": 370,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 393,
      "top": 337,
      "width": 370,
      "height": 173
    }
  },
  "plates": {
    "src": "/assets/skp/plates-369.webp",
    "srcset": "/assets/skp/plates-240.webp 240w, /assets/skp/plates-369.webp 369w",
    "width": 369,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 337,
      "width": 369,
      "height": 173
    }
  },
  "bowls": {
    "src": "/assets/skp/bowls-372.webp",
    "srcset": "/assets/skp/bowls-240.webp 240w, /assets/skp/bowls-372.webp 372w",
    "width": 372,
    "height": 173,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 1157,
      "top": 337,
      "width": 372,
      "height": 173
    }
  },
  "cutlery": {
    "src": "/assets/skp/cutlery-373.webp",
    "srcset": "/assets/skp/cutlery-240.webp 240w, /assets/skp/cutlery-373.webp 373w",
    "width": 373,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 8,
      "top": 569,
      "width": 373,
      "height": 153
    }
  },
  "food-containers": {
    "src": "/assets/skp/food-containers-370.webp",
    "srcset": "/assets/skp/food-containers-240.webp 240w, /assets/skp/food-containers-370.webp 370w",
    "width": 370,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 393,
      "top": 569,
      "width": 370,
      "height": 153
    }
  },
  "paper-products": {
    "src": "/assets/skp/paper-products-369.webp",
    "srcset": "/assets/skp/paper-products-240.webp 240w, /assets/skp/paper-products-369.webp 369w",
    "width": 369,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 569,
      "width": 369,
      "height": 153
    }
  },
  "thermoformed": {
    "src": "/assets/skp/thermoformed-372.webp",
    "srcset": "/assets/skp/thermoformed-240.webp 240w, /assets/skp/thermoformed-372.webp 372w",
    "width": 372,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 1157,
      "top": 569,
      "width": 372,
      "height": 153
    }
  },
  "custom-printed": {
    "src": "/assets/skp/custom-printed-181.webp",
    "srcset": "/assets/skp/custom-printed-181.webp 181w, /assets/skp/custom-printed-181.webp 181w",
    "width": 181,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 1348,
      "top": 714,
      "width": 181,
      "height": 174
    }
  },
  "specialty": {
    "src": "/assets/skp/specialty-369.webp",
    "srcset": "/assets/skp/specialty-240.webp 240w, /assets/skp/specialty-369.webp 369w",
    "width": 369,
    "height": 123,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 775,
      "top": 780,
      "width": 369,
      "height": 123
    }
  },
  "trays": {
    "src": "/assets/skp/trays-184.webp",
    "srcset": "/assets/skp/trays-184.webp 184w, /assets/skp/trays-184.webp 184w",
    "width": 184,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 762,
      "top": 714,
      "width": 184,
      "height": 174
    }
  },
  "clamshell": {
    "src": "/assets/skp/clamshell-180.webp",
    "srcset": "/assets/skp/clamshell-180.webp 180w, /assets/skp/clamshell-180.webp 180w",
    "width": 180,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 571,
      "top": 714,
      "width": 180,
      "height": 174
    }
  },
  "portion-cups": {
    "src": "/assets/skp/portion-cups-205.webp",
    "srcset": "/assets/skp/portion-cups-205.webp 205w, /assets/skp/portion-cups-205.webp 205w",
    "width": 205,
    "height": 176,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 1323,
      "top": 472,
      "width": 205,
      "height": 176
    }
  },
  "dessert-cups": {
    "src": "/assets/skp/dessert-cups-188.webp",
    "srcset": "/assets/skp/dessert-cups-188.webp 188w, /assets/skp/dessert-cups-188.webp 188w",
    "width": 188,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 8,
      "top": 714,
      "width": 188,
      "height": 174
    }
  },
  "takeaway": {
    "src": "/assets/skp/takeaway-185.webp",
    "srcset": "/assets/skp/takeaway-185.webp 185w, /assets/skp/takeaway-185.webp 185w",
    "width": 185,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 956,
      "top": 714,
      "width": 185,
      "height": 174
    }
  },
  "hero": {
    "src": "/assets/skp/hero-1101.webp",
    "srcset": "/assets/skp/hero-550.webp 550w, /assets/skp/hero-1101.webp 1101w",
    "width": 1101,
    "height": 327,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "crop": {
      "left": 435,
      "top": 0,
      "width": 1101,
      "height": 327
    }
  },
  "logo": {
    "src": "/assets/skp/logo-249.webp",
    "srcset": "/assets/skp/logo-249.webp 249w",
    "width": 249,
    "height": 89,
    "source": "ChatGPT Image Oct 1, 2026, 08_33_22 PM.png",
    "crop": {
      "left": 43,
      "top": 31,
      "width": 249,
      "height": 89
    }
  },
  "tissues": {
    "src": "/assets/skp/tissues-190.webp",
    "srcset": "/assets/skp/tissues-190.webp 190w, /assets/skp/tissues-190.webp 190w",
    "width": 190,
    "height": 174,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "crop": {
      "left": 1148,
      "top": 714,
      "width": 190,
      "height": 174
    }
  },
  "catalogue-08_29_50": {
    "src": "/assets/catalogues/08_29_50.webp",
    "srcset": "/assets/catalogues/08_29_50.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 08_29_50 PM.png",
    "status": "unverified"
  },
  "catalogue-08_30_10": {
    "src": "/assets/catalogues/08_30_10.webp",
    "srcset": "/assets/catalogues/08_30_10.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 08_30_10 PM.png",
    "status": "unverified"
  },
  "catalogue-08_33_22": {
    "src": "/assets/catalogues/08_33_22.webp",
    "srcset": "/assets/catalogues/08_33_22.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 08_33_22 PM.png",
    "status": "unverified"
  },
  "catalogue-10_18_40": {
    "src": "/assets/catalogues/10_18_40.webp",
    "srcset": "/assets/catalogues/10_18_40.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_40 PM.png",
    "status": "unverified"
  },
  "catalogue-10_18_49": {
    "src": "/assets/catalogues/10_18_49.webp",
    "srcset": "/assets/catalogues/10_18_49.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_49 PM.png",
    "status": "unverified"
  },
  "catalogue-10_18_54": {
    "src": "/assets/catalogues/10_18_54.webp",
    "srcset": "/assets/catalogues/10_18_54.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_54 PM.png",
    "status": "unverified"
  },
  "catalogue-10_19_00": {
    "src": "/assets/catalogues/10_19_00.webp",
    "srcset": "/assets/catalogues/10_19_00.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_00 PM.png",
    "status": "unverified"
  },
  "catalogue-10_19_04": {
    "src": "/assets/catalogues/10_19_04.webp",
    "srcset": "/assets/catalogues/10_19_04.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_04 PM.png",
    "status": "unverified"
  },
  "catalogue-10_19_08": {
    "src": "/assets/catalogues/10_19_08.webp",
    "srcset": "/assets/catalogues/10_19_08.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_08 PM.png",
    "status": "unverified"
  },
  "catalogue-10_19_33": {
    "src": "/assets/catalogues/10_19_33.webp",
    "srcset": "/assets/catalogues/10_19_33.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_33 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_11": {
    "src": "/assets/catalogues/10_20_11.webp",
    "srcset": "/assets/catalogues/10_20_11.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_11 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_15": {
    "src": "/assets/catalogues/10_20_15.webp",
    "srcset": "/assets/catalogues/10_20_15.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_15 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_31": {
    "src": "/assets/catalogues/10_20_31.webp",
    "srcset": "/assets/catalogues/10_20_31.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_31 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_34": {
    "src": "/assets/catalogues/10_20_34.webp",
    "srcset": "/assets/catalogues/10_20_34.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_34 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_38": {
    "src": "/assets/catalogues/10_20_38.webp",
    "srcset": "/assets/catalogues/10_20_38.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_38 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_43": {
    "src": "/assets/catalogues/10_20_43.webp",
    "srcset": "/assets/catalogues/10_20_43.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_46": {
    "src": "/assets/catalogues/10_20_46.webp",
    "srcset": "/assets/catalogues/10_20_46.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_50": {
    "src": "/assets/catalogues/10_20_50.webp",
    "srcset": "/assets/catalogues/10_20_50.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_50 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_53": {
    "src": "/assets/catalogues/10_20_53.webp",
    "srcset": "/assets/catalogues/10_20_53.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_53 PM.png",
    "status": "unverified"
  },
  "catalogue-10_20_57": {
    "src": "/assets/catalogues/10_20_57.webp",
    "srcset": "/assets/catalogues/10_20_57.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_57 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_01": {
    "src": "/assets/catalogues/10_21_01.webp",
    "srcset": "/assets/catalogues/10_21_01.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_01 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_05": {
    "src": "/assets/catalogues/10_21_05.webp",
    "srcset": "/assets/catalogues/10_21_05.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_05 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_08": {
    "src": "/assets/catalogues/10_21_08.webp",
    "srcset": "/assets/catalogues/10_21_08.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_08 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_12": {
    "src": "/assets/catalogues/10_21_12.webp",
    "srcset": "/assets/catalogues/10_21_12.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_12 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_33": {
    "src": "/assets/catalogues/10_21_33.webp",
    "srcset": "/assets/catalogues/10_21_33.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_33 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_37": {
    "src": "/assets/catalogues/10_21_37.webp",
    "srcset": "/assets/catalogues/10_21_37.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_37 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_41": {
    "src": "/assets/catalogues/10_21_41.webp",
    "srcset": "/assets/catalogues/10_21_41.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_41 PM.png",
    "status": "unverified"
  },
  "catalogue-10_21_47": {
    "src": "/assets/catalogues/10_21_47.webp",
    "srcset": "/assets/catalogues/10_21_47.webp 1536w",
    "width": 1536,
    "height": 1024,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_47 PM.png",
    "status": "unverified"
  },
  "cup-paper": {
    "src": "/assets/products/cups-glasses/cup-paper-485.webp",
    "srcset": "/assets/products/cups-glasses/cup-paper-240.webp 240w, /assets/products/cups-glasses/cup-paper-485.webp 485w",
    "width": 485,
    "height": 153,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_08 PM.png",
    "sourceCatalogue": "catalogue-10_21_08",
    "crop": {
      "left": 35,
      "top": 339,
      "width": 485,
      "height": 153
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "cup-clear": {
    "src": "/assets/products/cups-glasses/cup-clear-225.webp",
    "srcset": "/assets/products/cups-glasses/cup-clear-225.webp 225w",
    "width": 225,
    "height": 140,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_08 PM.png",
    "sourceCatalogue": "catalogue-10_21_08",
    "crop": {
      "left": 565,
      "top": 610,
      "width": 225,
      "height": 140
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "cup-textured": {
    "src": "/assets/products/cups-glasses/cup-textured-373.webp",
    "srcset": "/assets/products/cups-glasses/cup-textured-240.webp 240w, /assets/products/cups-glasses/cup-textured-373.webp 373w",
    "width": 373,
    "height": 145,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_08 PM.png",
    "sourceCatalogue": "catalogue-10_21_08",
    "crop": {
      "left": 1142,
      "top": 338,
      "width": 373,
      "height": 145
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "cup-print": {
    "src": "/assets/products/custom-products/cup-print-425.webp",
    "srcset": "/assets/products/custom-products/cup-print-240.webp 240w, /assets/products/custom-products/cup-print-425.webp 425w",
    "width": 425,
    "height": 141,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_08 PM.png",
    "sourceCatalogue": "catalogue-10_21_08",
    "crop": {
      "left": 1100,
      "top": 849,
      "width": 425,
      "height": 141
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "plate-round": {
    "src": "/assets/products/plates/plate-round-492.webp",
    "srcset": "/assets/products/plates/plate-round-240.webp 240w, /assets/products/plates/plate-round-492.webp 492w",
    "width": 492,
    "height": 144,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_05 PM.png",
    "sourceCatalogue": "catalogue-10_21_05",
    "crop": {
      "left": 25,
      "top": 276,
      "width": 492,
      "height": 144
    },
    "whitespaceMasks": [
      [
        0,
        0,
        355,
        20
      ],
      [
        0,
        0,
        43,
        26
      ]
    ],
    "status": "unverified"
  },
  "plate-square": {
    "src": "/assets/products/plates/plate-square-490.webp",
    "srcset": "/assets/products/plates/plate-square-240.webp 240w, /assets/products/plates/plate-square-490.webp 490w",
    "width": 490,
    "height": 120,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_05 PM.png",
    "sourceCatalogue": "catalogue-10_21_05",
    "crop": {
      "left": 23,
      "top": 491,
      "width": 490,
      "height": 120
    },
    "whitespaceMasks": [
      [
        0,
        0,
        375,
        23
      ],
      [
        0,
        0,
        48,
        26
      ]
    ],
    "status": "unverified"
  },
  "plate-compartment": {
    "src": "/assets/products/plates/plate-compartment-474.webp",
    "srcset": "/assets/products/plates/plate-compartment-240.webp 240w, /assets/products/plates/plate-compartment-474.webp 474w",
    "width": 474,
    "height": 134,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_05 PM.png",
    "sourceCatalogue": "catalogue-10_21_05",
    "crop": {
      "left": 1050,
      "top": 285,
      "width": 474,
      "height": 134
    },
    "whitespaceMasks": [
      [
        0,
        0,
        300,
        16
      ],
      [
        0,
        0,
        42,
        18
      ]
    ],
    "status": "unverified"
  },
  "plate-textured": {
    "src": "/assets/products/plates/plate-textured-485.webp",
    "srcset": "/assets/products/plates/plate-textured-240.webp 240w, /assets/products/plates/plate-textured-485.webp 485w",
    "width": 485,
    "height": 140,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_05 PM.png",
    "sourceCatalogue": "catalogue-10_21_05",
    "crop": {
      "left": 540,
      "top": 283,
      "width": 485,
      "height": 140
    },
    "whitespaceMasks": [
      [
        0,
        0,
        370,
        13
      ],
      [
        0,
        0,
        44,
        20
      ]
    ],
    "status": "unverified"
  },
  "tray-serving": {
    "src": "/assets/products/trays/tray-serving-673.webp",
    "srcset": "/assets/products/trays/tray-serving-240.webp 240w, /assets/products/trays/tray-serving-673.webp 673w",
    "width": 673,
    "height": 98,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_01 PM.png",
    "sourceCatalogue": "catalogue-10_21_01",
    "crop": {
      "left": 16,
      "top": 304,
      "width": 673,
      "height": 98
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "tray-square": {
    "src": "/assets/products/trays/tray-square-392.webp",
    "srcset": "/assets/products/trays/tray-square-240.webp 240w, /assets/products/trays/tray-square-392.webp 392w",
    "width": 392,
    "height": 103,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_01 PM.png",
    "sourceCatalogue": "catalogue-10_21_01",
    "crop": {
      "left": 705,
      "top": 299,
      "width": 392,
      "height": 103
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "tray-compartment": {
    "src": "/assets/products/trays/tray-compartment-586.webp",
    "srcset": "/assets/products/trays/tray-compartment-240.webp 240w, /assets/products/trays/tray-compartment-586.webp 586w",
    "width": 586,
    "height": 105,
    "source": "ChatGPT Image Oct 1, 2026, 10_21_01 PM.png",
    "sourceCatalogue": "catalogue-10_21_01",
    "crop": {
      "left": 12,
      "top": 494,
      "width": 586,
      "height": 105
    },
    "whitespaceMasks": [
      [
        0,
        0,
        180,
        17
      ]
    ],
    "status": "unverified"
  },
  "bowl-paper": {
    "src": "/assets/products/bowls/bowl-paper-514.webp",
    "srcset": "/assets/products/bowls/bowl-paper-240.webp 240w, /assets/products/bowls/bowl-paper-514.webp 514w",
    "width": 514,
    "height": 83,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_57 PM.png",
    "sourceCatalogue": "catalogue-10_20_57",
    "crop": {
      "left": 20,
      "top": 324,
      "width": 514,
      "height": 83
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bowl-plastic": {
    "src": "/assets/products/bowls/bowl-plastic-446.webp",
    "srcset": "/assets/products/bowls/bowl-plastic-240.webp 240w, /assets/products/bowls/bowl-plastic-446.webp 446w",
    "width": 446,
    "height": 84,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_57 PM.png",
    "sourceCatalogue": "catalogue-10_20_57",
    "crop": {
      "left": 1080,
      "top": 510,
      "width": 446,
      "height": 84
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "meal-round": {
    "src": "/assets/products/meal-trays/meal-round-738.webp",
    "srcset": "/assets/products/meal-trays/meal-round-240.webp 240w, /assets/products/meal-trays/meal-round-738.webp 738w",
    "width": 738,
    "height": 100,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_53 PM.png",
    "sourceCatalogue": "catalogue-10_20_53",
    "crop": {
      "left": 20,
      "top": 299,
      "width": 738,
      "height": 100
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "meal-divided": {
    "src": "/assets/products/meal-trays/meal-divided-728.webp",
    "srcset": "/assets/products/meal-trays/meal-divided-240.webp 240w, /assets/products/meal-trays/meal-divided-728.webp 728w",
    "width": 728,
    "height": 99,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_53 PM.png",
    "sourceCatalogue": "catalogue-10_20_53",
    "crop": {
      "left": 790,
      "top": 303,
      "width": 728,
      "height": 99
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "meal-lidded": {
    "src": "/assets/products/meal-trays/meal-lidded-415.webp",
    "srcset": "/assets/products/meal-trays/meal-lidded-240.webp 240w, /assets/products/meal-trays/meal-lidded-415.webp 415w",
    "width": 415,
    "height": 88,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_53 PM.png",
    "sourceCatalogue": "catalogue-10_20_53",
    "crop": {
      "left": 1105,
      "top": 505,
      "width": 415,
      "height": 88
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "cutlery-spoons": {
    "src": "/assets/products/cutlery/cutlery-spoons-330.webp",
    "srcset": "/assets/products/cutlery/cutlery-spoons-240.webp 240w, /assets/products/cutlery/cutlery-spoons-330.webp 330w",
    "width": 330,
    "height": 125,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_50 PM.png",
    "sourceCatalogue": "catalogue-10_20_50",
    "crop": {
      "left": 45,
      "top": 317,
      "width": 330,
      "height": 125
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "container-rectangular": {
    "src": "/assets/products/food-containers/container-rectangular-519.webp",
    "srcset": "/assets/products/food-containers/container-rectangular-240.webp 240w, /assets/products/food-containers/container-rectangular-519.webp 519w",
    "width": 519,
    "height": 85,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "sourceCatalogue": "catalogue-10_20_46",
    "crop": {
      "left": 18,
      "top": 515,
      "width": 519,
      "height": 85
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "container-round": {
    "src": "/assets/products/food-containers/container-round-453.webp",
    "srcset": "/assets/products/food-containers/container-round-240.webp 240w, /assets/products/food-containers/container-round-453.webp 453w",
    "width": 453,
    "height": 85,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "sourceCatalogue": "catalogue-10_20_46",
    "crop": {
      "left": 566,
      "top": 520,
      "width": 453,
      "height": 85
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "container-clear": {
    "src": "/assets/products/food-containers/container-clear-357.webp",
    "srcset": "/assets/products/food-containers/container-clear-240.webp 240w, /assets/products/food-containers/container-clear-357.webp 357w",
    "width": 357,
    "height": 90,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "sourceCatalogue": "catalogue-10_20_46",
    "crop": {
      "left": 1164,
      "top": 704,
      "width": 357,
      "height": 90
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "clamshell-rectangular": {
    "src": "/assets/products/clamshell-containers/clamshell-rectangular-583.webp",
    "srcset": "/assets/products/clamshell-containers/clamshell-rectangular-240.webp 240w, /assets/products/clamshell-containers/clamshell-rectangular-583.webp 583w",
    "width": 583,
    "height": 102,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "sourceCatalogue": "catalogue-10_20_46",
    "crop": {
      "left": 21,
      "top": 313,
      "width": 583,
      "height": 102
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "clamshell-square": {
    "src": "/assets/products/clamshell-containers/clamshell-square-460.webp",
    "srcset": "/assets/products/clamshell-containers/clamshell-square-240.webp 240w, /assets/products/clamshell-containers/clamshell-square-460.webp 460w",
    "width": 460,
    "height": 101,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_46 PM.png",
    "sourceCatalogue": "catalogue-10_20_46",
    "crop": {
      "left": 626,
      "top": 314,
      "width": 460,
      "height": 101
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "portion-round": {
    "src": "/assets/products/portion-sauce-cups/portion-round-529.webp",
    "srcset": "/assets/products/portion-sauce-cups/portion-round-240.webp 240w, /assets/products/portion-sauce-cups/portion-round-529.webp 529w",
    "width": 529,
    "height": 91,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 17,
      "top": 304,
      "width": 529,
      "height": 91
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "portion-square": {
    "src": "/assets/products/portion-sauce-cups/portion-square-415.webp",
    "srcset": "/assets/products/portion-sauce-cups/portion-square-240.webp 240w, /assets/products/portion-sauce-cups/portion-square-415.webp 415w",
    "width": 415,
    "height": 91,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 1105,
      "top": 311,
      "width": 415,
      "height": 91
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "sauce-lidded": {
    "src": "/assets/products/portion-sauce-cups/sauce-lidded-490.webp",
    "srcset": "/assets/products/portion-sauce-cups/sauce-lidded-240.webp 240w, /assets/products/portion-sauce-cups/sauce-lidded-490.webp 490w",
    "width": 490,
    "height": 82,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 580,
      "top": 312,
      "width": 490,
      "height": 82
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "dessert-clear": {
    "src": "/assets/products/dessert-ice-cream-cups/dessert-clear-531.webp",
    "srcset": "/assets/products/dessert-ice-cream-cups/dessert-clear-240.webp 240w, /assets/products/dessert-ice-cream-cups/dessert-clear-531.webp 531w",
    "width": 531,
    "height": 94,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 19,
      "top": 494,
      "width": 531,
      "height": 94
    },
    "whitespaceMasks": [
      [
        0,
        0,
        50,
        10
      ]
    ],
    "status": "unverified"
  },
  "dessert-opaque": {
    "src": "/assets/products/dessert-ice-cream-cups/dessert-opaque-494.webp",
    "srcset": "/assets/products/dessert-ice-cream-cups/dessert-opaque-240.webp 240w, /assets/products/dessert-ice-cream-cups/dessert-opaque-494.webp 494w",
    "width": 494,
    "height": 92,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 579,
      "top": 499,
      "width": 494,
      "height": 92
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "ice-cream-printed": {
    "src": "/assets/products/dessert-ice-cream-cups/ice-cream-printed-422.webp",
    "srcset": "/assets/products/dessert-ice-cream-cups/ice-cream-printed-240.webp 240w, /assets/products/dessert-ice-cream-cups/ice-cream-printed-422.webp 422w",
    "width": 422,
    "height": 91,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 1100,
      "top": 499,
      "width": 422,
      "height": 91
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "utility-serving-cups": {
    "src": "/assets/products/utility-cups/utility-serving-cups-509.webp",
    "srcset": "/assets/products/utility-cups/utility-serving-cups-240.webp 240w, /assets/products/utility-cups/utility-serving-cups-509.webp 509w",
    "width": 509,
    "height": 96,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_43 PM.png",
    "sourceCatalogue": "catalogue-10_20_43",
    "crop": {
      "left": 585,
      "top": 691,
      "width": 509,
      "height": 96
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "foil-rectangular": {
    "src": "/assets/products/aluminium-foil/foil-rectangular-574.webp",
    "srcset": "/assets/products/aluminium-foil/foil-rectangular-240.webp 240w, /assets/products/aluminium-foil/foil-rectangular-574.webp 574w",
    "width": 574,
    "height": 96,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_38 PM.png",
    "sourceCatalogue": "catalogue-10_20_38",
    "crop": {
      "left": 17,
      "top": 305,
      "width": 574,
      "height": 96
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "foil-round": {
    "src": "/assets/products/aluminium-foil/foil-round-572.webp",
    "srcset": "/assets/products/aluminium-foil/foil-round-240.webp 240w, /assets/products/aluminium-foil/foil-round-572.webp 572w",
    "width": 572,
    "height": 98,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_38 PM.png",
    "sourceCatalogue": "catalogue-10_20_38",
    "crop": {
      "left": 19,
      "top": 500,
      "width": 572,
      "height": 98
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "foil-divided": {
    "src": "/assets/products/aluminium-foil/foil-divided-363.webp",
    "srcset": "/assets/products/aluminium-foil/foil-divided-240.webp 240w, /assets/products/aluminium-foil/foil-divided-363.webp 363w",
    "width": 363,
    "height": 88,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_38 PM.png",
    "sourceCatalogue": "catalogue-10_20_38",
    "crop": {
      "left": 1157,
      "top": 506,
      "width": 363,
      "height": 88
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "takeaway-boxes": {
    "src": "/assets/products/takeaway-packaging/takeaway-boxes-375.webp",
    "srcset": "/assets/products/takeaway-packaging/takeaway-boxes-240.webp 240w, /assets/products/takeaway-packaging/takeaway-boxes-375.webp 375w",
    "width": 375,
    "height": 88,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_34 PM.png",
    "sourceCatalogue": "catalogue-10_20_34",
    "crop": {
      "left": 20,
      "top": 287,
      "width": 375,
      "height": 88
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "takeaway-snack": {
    "src": "/assets/products/takeaway-packaging/takeaway-snack-357.webp",
    "srcset": "/assets/products/takeaway-packaging/takeaway-snack-240.webp 240w, /assets/products/takeaway-packaging/takeaway-snack-357.webp 357w",
    "width": 357,
    "height": 95,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_34 PM.png",
    "sourceCatalogue": "catalogue-10_20_34",
    "crop": {
      "left": 818,
      "top": 686,
      "width": 357,
      "height": 95
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "sweet-window": {
    "src": "/assets/products/sweets-packaging/sweet-window-418.webp",
    "srcset": "/assets/products/sweets-packaging/sweet-window-240.webp 240w, /assets/products/sweets-packaging/sweet-window-418.webp 418w",
    "width": 418,
    "height": 111,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_31 PM.png",
    "sourceCatalogue": "catalogue-10_20_31",
    "crop": {
      "left": 1105,
      "top": 303,
      "width": 418,
      "height": 111
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "sweet-gift": {
    "src": "/assets/products/sweets-packaging/sweet-gift-484.webp",
    "srcset": "/assets/products/sweets-packaging/sweet-gift-240.webp 240w, /assets/products/sweets-packaging/sweet-gift-484.webp 484w",
    "width": 484,
    "height": 111,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_31 PM.png",
    "sourceCatalogue": "catalogue-10_20_31",
    "crop": {
      "left": 604,
      "top": 303,
      "width": 484,
      "height": 111
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "sweet-divided": {
    "src": "/assets/products/sweets-packaging/sweet-divided-499.webp",
    "srcset": "/assets/products/sweets-packaging/sweet-divided-240.webp 240w, /assets/products/sweets-packaging/sweet-divided-499.webp 499w",
    "width": 499,
    "height": 99,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_31 PM.png",
    "sourceCatalogue": "catalogue-10_20_31",
    "crop": {
      "left": 559,
      "top": 510,
      "width": 499,
      "height": 99
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bakery-boxes": {
    "src": "/assets/products/bakery-packaging/bakery-boxes-516.webp",
    "srcset": "/assets/products/bakery-packaging/bakery-boxes-240.webp 240w, /assets/products/bakery-packaging/bakery-boxes-516.webp 516w",
    "width": 516,
    "height": 110,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_15 PM.png",
    "sourceCatalogue": "catalogue-10_20_15",
    "crop": {
      "left": 19,
      "top": 285,
      "width": 516,
      "height": 110
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bakery-domes": {
    "src": "/assets/products/bakery-packaging/bakery-domes-516.webp",
    "srcset": "/assets/products/bakery-packaging/bakery-domes-240.webp 240w, /assets/products/bakery-packaging/bakery-domes-516.webp 516w",
    "width": 516,
    "height": 105,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_15 PM.png",
    "sourceCatalogue": "catalogue-10_20_15",
    "crop": {
      "left": 18,
      "top": 482,
      "width": 516,
      "height": 105
    },
    "whitespaceMasks": [
      [
        0,
        0,
        400,
        7
      ]
    ],
    "status": "unverified"
  },
  "bakery-slices": {
    "src": "/assets/products/bakery-packaging/bakery-slices-414.webp",
    "srcset": "/assets/products/bakery-packaging/bakery-slices-240.webp 240w, /assets/products/bakery-packaging/bakery-slices-414.webp 414w",
    "width": 414,
    "height": 99,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_15 PM.png",
    "sourceCatalogue": "catalogue-10_20_15",
    "crop": {
      "left": 1107,
      "top": 486,
      "width": 414,
      "height": 99
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "areca-round": {
    "src": "/assets/products/areca/areca-round-579.webp",
    "srcset": "/assets/products/areca/areca-round-240.webp 240w, /assets/products/areca/areca-round-579.webp 579w",
    "width": 579,
    "height": 115,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_11 PM.png",
    "sourceCatalogue": "catalogue-10_20_11",
    "crop": {
      "left": 17,
      "top": 295,
      "width": 579,
      "height": 115
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "areca-square": {
    "src": "/assets/products/areca/areca-square-430.webp",
    "srcset": "/assets/products/areca/areca-square-240.webp 240w, /assets/products/areca/areca-square-430.webp 430w",
    "width": 430,
    "height": 106,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_11 PM.png",
    "sourceCatalogue": "catalogue-10_20_11",
    "crop": {
      "left": 628,
      "top": 301,
      "width": 430,
      "height": 106
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "areca-bowls": {
    "src": "/assets/products/areca/areca-bowls-477.webp",
    "srcset": "/assets/products/areca/areca-bowls-240.webp 240w, /assets/products/areca/areca-bowls-477.webp 477w",
    "width": 477,
    "height": 80,
    "source": "ChatGPT Image Oct 1, 2026, 10_20_11 PM.png",
    "sourceCatalogue": "catalogue-10_20_11",
    "crop": {
      "left": 1042,
      "top": 500,
      "width": 477,
      "height": 80
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bagasse-plates": {
    "src": "/assets/products/bagasse/bagasse-plates-492.webp",
    "srcset": "/assets/products/bagasse/bagasse-plates-240.webp 240w, /assets/products/bagasse/bagasse-plates-492.webp 492w",
    "width": 492,
    "height": 89,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_33 PM.png",
    "sourceCatalogue": "catalogue-10_19_33",
    "crop": {
      "left": 17,
      "top": 264,
      "width": 492,
      "height": 89
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bagasse-hinged": {
    "src": "/assets/products/bagasse/bagasse-hinged-236.webp",
    "srcset": "/assets/products/bagasse/bagasse-hinged-236.webp 236w",
    "width": 236,
    "height": 84,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_33 PM.png",
    "sourceCatalogue": "catalogue-10_19_33",
    "crop": {
      "left": 539,
      "top": 597,
      "width": 236,
      "height": 84
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bagasse-trays": {
    "src": "/assets/products/bagasse/bagasse-trays-493.webp",
    "srcset": "/assets/products/bagasse/bagasse-trays-240.webp 240w, /assets/products/bagasse/bagasse-trays-493.webp 493w",
    "width": 493,
    "height": 81,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_33 PM.png",
    "sourceCatalogue": "catalogue-10_19_33",
    "crop": {
      "left": 14,
      "top": 599,
      "width": 493,
      "height": 81
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "kraft-burger": {
    "src": "/assets/products/kraft-packaging/kraft-burger-399.webp",
    "srcset": "/assets/products/kraft-packaging/kraft-burger-240.webp 240w, /assets/products/kraft-packaging/kraft-burger-399.webp 399w",
    "width": 399,
    "height": 114,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_08 PM.png",
    "sourceCatalogue": "catalogue-10_19_08",
    "crop": {
      "left": 19,
      "top": 304,
      "width": 399,
      "height": 114
    },
    "whitespaceMasks": [
      [
        0,
        0,
        210,
        4
      ]
    ],
    "status": "unverified"
  },
  "kraft-bowls": {
    "src": "/assets/products/kraft-packaging/kraft-bowls-425.webp",
    "srcset": "/assets/products/kraft-packaging/kraft-bowls-240.webp 240w, /assets/products/kraft-packaging/kraft-bowls-425.webp 425w",
    "width": 425,
    "height": 83,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_08 PM.png",
    "sourceCatalogue": "catalogue-10_19_08",
    "crop": {
      "left": 16,
      "top": 521,
      "width": 425,
      "height": 83
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "kraft-meal": {
    "src": "/assets/products/kraft-packaging/kraft-meal-346.webp",
    "srcset": "/assets/products/kraft-packaging/kraft-meal-240.webp 240w, /assets/products/kraft-packaging/kraft-meal-346.webp 346w",
    "width": 346,
    "height": 100,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_08 PM.png",
    "sourceCatalogue": "catalogue-10_19_08",
    "crop": {
      "left": 850,
      "top": 514,
      "width": 346,
      "height": 100
    },
    "whitespaceMasks": [
      [
        0,
        0,
        100,
        4
      ]
    ],
    "status": "unverified"
  },
  "bag-handled": {
    "src": "/assets/products/paper-bags/bag-handled-205.webp",
    "srcset": "/assets/products/paper-bags/bag-handled-205.webp 205w",
    "width": 205,
    "height": 131,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_04 PM.png",
    "sourceCatalogue": "catalogue-10_19_04",
    "crop": {
      "left": 861,
      "top": 320,
      "width": 205,
      "height": 131
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bag-flat": {
    "src": "/assets/products/paper-bags/bag-flat-409.webp",
    "srcset": "/assets/products/paper-bags/bag-flat-240.webp 240w, /assets/products/paper-bags/bag-flat-409.webp 409w",
    "width": 409,
    "height": 128,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_04 PM.png",
    "sourceCatalogue": "catalogue-10_19_04",
    "crop": {
      "left": 25,
      "top": 324,
      "width": 409,
      "height": 128
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bag-diecut": {
    "src": "/assets/products/paper-bags/bag-diecut-387.webp",
    "srcset": "/assets/products/paper-bags/bag-diecut-240.webp 240w, /assets/products/paper-bags/bag-diecut-387.webp 387w",
    "width": 387,
    "height": 129,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_04 PM.png",
    "sourceCatalogue": "catalogue-10_19_04",
    "crop": {
      "left": 21,
      "top": 526,
      "width": 387,
      "height": 129
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "tissue-napkins": {
    "src": "/assets/products/tissues/tissue-napkins-374.webp",
    "srcset": "/assets/products/tissues/tissue-napkins-240.webp 240w, /assets/products/tissues/tissue-napkins-374.webp 374w",
    "width": 374,
    "height": 92,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_00 PM.png",
    "sourceCatalogue": "catalogue-10_19_00",
    "crop": {
      "left": 778,
      "top": 310,
      "width": 374,
      "height": 92
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "tissue-boxes": {
    "src": "/assets/products/tissues/tissue-boxes-372.webp",
    "srcset": "/assets/products/tissues/tissue-boxes-240.webp 240w, /assets/products/tissues/tissue-boxes-372.webp 372w",
    "width": 372,
    "height": 103,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_00 PM.png",
    "sourceCatalogue": "catalogue-10_19_00",
    "crop": {
      "left": 21,
      "top": 306,
      "width": 372,
      "height": 103
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "tissue-dinner": {
    "src": "/assets/products/tissues/tissue-dinner-307.webp",
    "srcset": "/assets/products/tissues/tissue-dinner-240.webp 240w, /assets/products/tissues/tissue-dinner-307.webp 307w",
    "width": 307,
    "height": 96,
    "source": "ChatGPT Image Oct 1, 2026, 10_19_00 PM.png",
    "sourceCatalogue": "catalogue-10_19_00",
    "crop": {
      "left": 424,
      "top": 508,
      "width": 307,
      "height": 96
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "wood-spoons": {
    "src": "/assets/products/wooden-bamboo/wood-spoons-445.webp",
    "srcset": "/assets/products/wooden-bamboo/wood-spoons-240.webp 240w, /assets/products/wooden-bamboo/wood-spoons-445.webp 445w",
    "width": 445,
    "height": 123,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_54 PM.png",
    "sourceCatalogue": "catalogue-10_18_54",
    "crop": {
      "left": 28,
      "top": 295,
      "width": 445,
      "height": 123
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "wood-forks": {
    "src": "/assets/products/wooden-bamboo/wood-forks-257.webp",
    "srcset": "/assets/products/wooden-bamboo/wood-forks-240.webp 240w, /assets/products/wooden-bamboo/wood-forks-257.webp 257w",
    "width": 257,
    "height": 122,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_54 PM.png",
    "sourceCatalogue": "catalogue-10_18_54",
    "crop": {
      "left": 513,
      "top": 295,
      "width": 257,
      "height": 122
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "bamboo-chopsticks": {
    "src": "/assets/products/wooden-bamboo/bamboo-chopsticks-253.webp",
    "srcset": "/assets/products/wooden-bamboo/bamboo-chopsticks-240.webp 240w, /assets/products/wooden-bamboo/bamboo-chopsticks-253.webp 253w",
    "width": 253,
    "height": 110,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_54 PM.png",
    "sourceCatalogue": "catalogue-10_18_54",
    "crop": {
      "left": 341,
      "top": 500,
      "width": 253,
      "height": 110
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "lid-cups": {
    "src": "/assets/products/lids-accessories/lid-cups-532.webp",
    "srcset": "/assets/products/lids-accessories/lid-cups-240.webp 240w, /assets/products/lids-accessories/lid-cups-532.webp 532w",
    "width": 532,
    "height": 72,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_49 PM.png",
    "sourceCatalogue": "catalogue-10_18_49",
    "crop": {
      "left": 15,
      "top": 300,
      "width": 532,
      "height": 72
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "lid-flat-dome": {
    "src": "/assets/products/lids-accessories/lid-flat-dome-451.webp",
    "srcset": "/assets/products/lids-accessories/lid-flat-dome-240.webp 240w, /assets/products/lids-accessories/lid-flat-dome-451.webp 451w",
    "width": 451,
    "height": 79,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_49 PM.png",
    "sourceCatalogue": "catalogue-10_18_49",
    "crop": {
      "left": 575,
      "top": 293,
      "width": 451,
      "height": 79
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "lid-containers": {
    "src": "/assets/products/lids-accessories/lid-containers-484.webp",
    "srcset": "/assets/products/lids-accessories/lid-containers-240.webp 240w, /assets/products/lids-accessories/lid-containers-484.webp 484w",
    "width": 484,
    "height": 82,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_49 PM.png",
    "sourceCatalogue": "catalogue-10_18_49",
    "crop": {
      "left": 16,
      "top": 484,
      "width": 484,
      "height": 82
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "catering-round": {
    "src": "/assets/products/catering-range/catering-round-393.webp",
    "srcset": "/assets/products/catering-range/catering-round-240.webp 240w, /assets/products/catering-range/catering-round-393.webp 393w",
    "width": 393,
    "height": 97,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_40 PM.png",
    "sourceCatalogue": "catalogue-10_18_40",
    "crop": {
      "left": 20,
      "top": 296,
      "width": 393,
      "height": 97
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "catering-square": {
    "src": "/assets/products/catering-range/catering-square-347.webp",
    "srcset": "/assets/products/catering-range/catering-square-240.webp 240w, /assets/products/catering-range/catering-square-347.webp 347w",
    "width": 347,
    "height": 77,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_40 PM.png",
    "sourceCatalogue": "catalogue-10_18_40",
    "crop": {
      "left": 437,
      "top": 308,
      "width": 347,
      "height": 77
    },
    "whitespaceMasks": [],
    "status": "unverified"
  },
  "catering-set": {
    "src": "/assets/products/catering-range/catering-set-297.webp",
    "srcset": "/assets/products/catering-range/catering-set-240.webp 240w, /assets/products/catering-range/catering-set-297.webp 297w",
    "width": 297,
    "height": 108,
    "source": "ChatGPT Image Oct 1, 2026, 10_18_40 PM.png",
    "sourceCatalogue": "catalogue-10_18_40",
    "crop": {
      "left": 901,
      "top": 791,
      "width": 297,
      "height": 108
    },
    "whitespaceMasks": [],
    "status": "unverified"
  }
};
export const categoryImages={"cups-glasses":"cup-paper","plates":"plate-round","trays":"tray-serving","bowls":"bowl-paper","meal-trays":"meal-round","cutlery":"cutlery-spoons","food-containers":"container-rectangular","clamshell-containers":"clamshell-rectangular","portion-sauce-cups":"portion-round","dessert-ice-cream-cups":"dessert-clear","utility-cups":"utility-serving-cups","aluminium-foil":"foil-rectangular","takeaway-packaging":"takeaway-boxes","sweets-packaging":"sweet-window","bakery-packaging":"bakery-boxes","areca":"areca-round","bagasse":"bagasse-plates","kraft-packaging":"kraft-burger","paper-bags":"bag-handled","tissues":"tissue-napkins","wooden-bamboo":"wood-spoons","lids-accessories":"lid-cups","catering-range":"catering-round","custom-products":"cup-print","thermoformed-products":"thermoformed","paper-products":"tissue-napkins","specialty-products":"thermoformed","plates-trays":"plate-round"};
export const productImages={"paper-cups":"cup-paper","printed-paper-cups":"cup-print","100ml-tea-cup":"cup-paper","disposable-juice-glass":"cup-clear","water-plastic-glass":"cup-clear","plastic-cups":"cup-clear","paper-bowls":"bowl-paper","plastic-bowls":"bowl-plastic","paper-plates":"plate-round","disposable-spoons-forks":"cutlery-spoons","table-tissues":"tissue-napkins"};
export const heroImages={home:'hero',custom:'cup-print'};
export const industryImages={};
