import {createEnquiryStore} from './enquiryStore.js';
const key='skp-enquiry-v1';
export function initPlatform(config){
 let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{}};}
 const store=createEnquiryStore({storage,knownIds:config.products.map(p=>p.slug)});let sampleItems=[];
 const sampleRoot=document.querySelector('[data-sample-items]'),listRoot=document.querySelector('[data-enquiry-items]');
 const create=(tag,text,cls)=>{const el=document.createElement(tag);if(text)el.textContent=text;if(cls)el.className=cls;return el;};
 function itemRows(root,items,samples=false){if(!root)return;root.replaceChildren();for(const item of items){const p=config.products.find(p=>p.slug===item.productId);if(!p)continue;const article=create('article',null,'enquiry-item');if(p.image){const img=create('img');img.src=p.image;img.alt=p.name;img.width=160;img.height=120;img.loading='lazy';article.append(img);}const body=create('div');body.append(create('h3',p.name));const link=create('a','View Details','text-link');link.href='/products/'+p.slug;body.append(link);const grid=create('div',null,'enquiry-item-fields');if(!samples){const label=create('label','Estimated Quantity');const input=create('input');input.type='number';input.min='1';input.max='999999999';input.step='1';input.value=item.quantity;input.dataset.quantity=item.productId;input.addEventListener('input',()=>store.update(item.productId,{quantity:input.value}));label.append(input);grid.append(label);}const notesLabel=create('label',samples?'Sample requirement / notes':'Requirement / Notes');const notes=create('textarea');notes.rows=2;notes.maxLength=1500;notes.value=item.notes;notes.dataset.userContent='true';notes.addEventListener('input',()=>samples?sampleItems=sampleItems.map(x=>x.productId===item.productId?{...x,notes:notes.value}:x):store.update(item.productId,{notes:notes.value}));notesLabel.append(notes);grid.append(notesLabel);body.append(grid);article.append(body);const remove=create('button','Remove','text-link');remove.type='button';remove.setAttribute('aria-label','Remove '+p.name);remove.addEventListener('click',()=>{if(samples){sampleItems=sampleItems.filter(x=>x.productId!==item.productId);itemRows(sampleRoot,sampleItems,true);}else{store.remove(item.productId);refresh();}});article.append(remove);root.append(article);}document.dispatchEvent(new Event('skp:content'));}
 function refresh(){const items=store.read();document.querySelectorAll('[data-enquiry-count]').forEach(e=>e.textContent=String(items.length));document.querySelectorAll('[data-enquiry-access]').forEach(e=>e.hidden=!items.length);document.querySelectorAll('[data-add-enquiry]').forEach(b=>{const added=items.some(x=>x.productId===b.dataset.addEnquiry);b.textContent=added?'In Enquiry List':'Add to Enquiry';b.setAttribute('aria-pressed',String(added));});if(listRoot)itemRows(listRoot,items);document.querySelector('[data-enquiry-empty]')?.toggleAttribute('hidden',Boolean(items.length));document.querySelector('.enquiry-buyer')?.toggleAttribute('hidden',!items.length);const storageNote=document.querySelector('[data-storage-note]');if(storageNote){storageNote.hidden=!items.length;storageNote.textContent=store.persistent?'Your selections are saved on this device. Contact details are not stored.':'Your selections are kept for this visit. Browser storage is unavailable.';}document.dispatchEvent(new Event('skp:content'));}
 document.querySelectorAll('[data-add-enquiry]').forEach(button=>button.addEventListener('click',()=>{store.add(button.dataset.addEnquiry);refresh();const status=document.querySelector('#enquiry-feedback');status.textContent='Added to your Enquiry List.';document.dispatchEvent(new Event('skp:content'));}));
 const multiForm=document.querySelector('[data-multi-form] form');if(multiForm){multiForm.dataset.platform='enquiry';multiForm.id='bulk-enquiry-form';const requirement=multiForm.querySelector('fieldset:nth-of-type(2)');const message=requirement.querySelector('label.full');requirement.before(message);requirement.hidden=true;multiForm.querySelector('[type=submit]').textContent='Request Bulk Quote';const intent=document.querySelector('#list-intent');const initial=new URLSearchParams(location.search).get('kind');if(initial==='Export enquiry')intent.value=initial;const setIntent=()=>{multiForm.elements.enquiryType.value=intent.value;multiForm.elements.pathway.value=intent.value;};intent.addEventListener('change',setIntent);setIntent();multiForm.addEventListener('submit',e=>{if(!store.read().length||[...document.querySelectorAll('[data-quantity]')].some(x=>!x.reportValidity())){e.preventDefault();e.stopImmediatePropagation();multiForm.querySelector('.form-status').textContent=store.read().length?'Enter a positive whole quantity or leave it blank.':'Add a product family before preparing your enquiry.';document.dispatchEvent(new Event('skp:content'));}},true);}
 const sampleForm=document.querySelector('[data-sample-form] form');if(sampleForm){sampleForm.dataset.platform='sample';sampleForm.id='sample-request-form';const messageLabel=sampleForm.elements.message.closest('label');for(const field of document.querySelectorAll('[form=sample-request-form]')){const label=field.closest('label');label.classList.add('full');messageLabel.before(label);}sampleForm.elements.enquiryType.value='Sample request';sampleForm.elements.product.closest('label').hidden=true;sampleForm.elements.category.closest('label').hidden=true;sampleForm.querySelector('[type=submit]').textContent='Request Samples';const params=new URLSearchParams(location.search);sampleItems=params.get('from')==='list'?store.read().map(x=>({...x})):[];const product=params.get('product'),category=params.get('category');if(config.products.some(p=>p.slug===product))sampleItems=[{productId:product,notes:''}];const select=document.querySelector('#sample-product');for(const p of config.products.filter(p=>!p.slug.endsWith('-enquiry')&&(!category||p.category===category))){const option=create('option',p.name);option.value=p.slug;select.append(option);}document.querySelector('#add-sample-product').addEventListener('click',()=>{if(select.value&&!sampleItems.some(x=>x.productId===select.value)){sampleItems.push({productId:select.value,notes:''});itemRows(sampleRoot,sampleItems,true);}});itemRows(sampleRoot,sampleItems,true);sampleForm.addEventListener('submit',e=>{if(!sampleItems.length){e.preventDefault();e.stopImmediatePropagation();sampleForm.querySelector('.form-status').textContent='Select a product family for your sample request.';document.dispatchEvent(new Event('skp:content'));}},true);}
 addEventListener('storage',e=>{if(e.key===key)refresh();});refresh();
 return {payload(form){if(!form.dataset.platform)return null;const items=(form.dataset.platform==='sample'?sampleItems:store.read()).map(x=>({...x,name:config.products.find(p=>p.slug===x.productId)?.name,category:config.products.find(p=>p.slug===x.productId)?.category}));return {type:form.dataset.platform,items};}};
}
