import {company,categories,products,industries,solutions,pages,routes} from './data.js';import {legalPages} from './data/pages.js';import {esc} from './components/ui.js';import {catalogue,detail} from './components/catalogue.js';import {home,general,industryPage,solutionPage,contact,rfq,legal,notFound} from './components/pages.js';import {header,footer} from './components/layout.js';
export {esc} from './components/ui.js';export {quote} from './components/ui.js';export {form} from './components/forms.js';
export function content(path){
 if(path==='/')return home();
 if(path==='/products'||categories.some(c=>path==='/products/'+c.slug))return catalogue(path);
 const p=products.find(p=>path==='/products/'+p.slug);if(p)return detail(p);
 if(path==='/industries'||industries.some(i=>path==='/industries/'+i.slug))return industryPage(path);
 if(path==='/solutions'||solutions.some(s=>path==='/solutions/'+s.slug))return solutionPage(path);
 if(pages[path.slice(1)])return general(path.slice(1));
 if(path==='/contact')return contact();if(path==='/rfq')return rfq();if(legalPages[path.slice(1)])return legal(path.slice(1));return notFound();
}
export function metadata(path,baseUrl=company.url){
 const product=products.find(p=>path==='/products/'+p.slug),category=categories.find(c=>path==='/products/'+c.slug),industry=industries.find(i=>path==='/industries/'+i.slug),solution=solutions.find(s=>path==='/solutions/'+s.slug),page=pages[path.slice(1)]||legalPages[path.slice(1)];
 const known=routes.includes(path);const defaults={
 '/':['Foodservice Disposables & Paper Cup Manufacturing','Explore SKP paper cups, plastic beverage formats, tableware and custom paper cup enquiries with M/s S. K. Thermoformers, Khairthal, Rajasthan.'],
 '/products':['SKP Product Catalogue','Explore listed SKP foodservice products by category, material and application. Request current specifications and a bulk supply quote.'],
 '/solutions':['Foodservice Application Solutions','Find SKP product families for beverage service, catering, institutional foodservice and custom paper cup branding enquiries.'],
 '/industries':['Markets We Serve','Explore foodservice buying requirements for restaurants, hospitality, catering, institutions and distributors with SK Thermoformers.'],
 '/contact':['Contact SK Thermoformers','Contact M/s S. K. Thermoformers in Khairthal, Rajasthan, about bulk foodservice products, custom paper cups and export enquiries.'],
 '/rfq':['Request a Quote','Share your product, application, quantity and destination with SK Thermoformers. Prepare a business enquiry for specifications and availability.']
 };
 const label=product?.name||category?.name||(industry?industry.name+' - Market Enquiries':null)||(solution?solution.name+' - Solutions':null)||page?.title||defaults[path]?.[0]||'Page Not Found';
 const description=product?.description||(category?`Explore ${category.name.toLowerCase()} with SKP. ${category.description} Confirm current product availability and specifications with the team.`:null)||industry?.detail||solution?.detail||page?.intro||defaults[path]?.[1]||'Explore SKP products or contact SK Thermoformers about your requirement.';
 const url=baseUrl.replace(/\/$/,'')+(path==='/'?'':path);const image=baseUrl.replace(/\/$/,'')+'/assets/social.jpg';
 const schema=[{'@context':'https://schema.org','@type':'Organization',name:company.legalName,alternateName:'SKP',url:baseUrl,email:company.email,telephone:company.phone,logo:baseUrl+'/assets/skp/logo-249.webp',address:{'@type':'PostalAddress',streetAddress:'Harsoli Road, Near Shailja Grits Udyog, Khairthal',addressLocality:'Alwar',addressRegion:'Rajasthan',postalCode:'301404',addressCountry:'IN'}},{'@context':'https://schema.org','@type':'WebSite',name:'SKP - S. K. Thermoformers',url:baseUrl}];
 if(product&&product.status==='listed')schema.push({'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,material:product.material||undefined,sku:product.sku||undefined,brand:{'@type':'Brand',name:'SKP'}});
 if(known&&path!=='/'){const crumbs=[{name:'Home',url:baseUrl}];if(product){crumbs.push({name:'Products',url:baseUrl+'/products'},{name:categories.find(c=>c.slug===product.category).name,url:baseUrl+'/products/'+product.category});}else if(category)crumbs.push({name:'Products',url:baseUrl+'/products'});else if(industry)crumbs.push({name:'Industries',url:baseUrl+'/industries'});else if(solution)crumbs.push({name:'Solutions',url:baseUrl+'/solutions'});crumbs.push({name:label,url});schema.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:c.url}))});}
 return {title:label+' | S. K. Thermoformers',description,url,image,schema,known};
}
export function render(path='/',{baseUrl=company.url}={}){const m=metadata(path,baseUrl);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(m.title)}</title><meta name="description" content="${esc(m.description)}">${m.known?`<link rel="canonical" href="${esc(m.url)}">`:'<meta name="robots" content="noindex,follow">'}<meta property="og:title" content="${esc(m.title)}"><meta property="og:description" content="${esc(m.description)}"><meta property="og:url" content="${esc(m.url)}"><meta property="og:type" content="website"><meta property="og:site_name" content="SKP - S. K. Thermoformers"><meta property="og:image" content="${esc(m.image)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="SKP foodservice disposables - business enquiries"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(m.title)}"><meta name="twitter:description" content="${esc(m.description)}"><meta name="twitter:image" content="${esc(m.image)}"><meta name="theme-color" content="#c90019"><link rel="icon" href="/assets/favicon.png"><link rel="stylesheet" href="/src/styles.css"><script type="application/ld+json">${JSON.stringify(m.schema).replaceAll('<','\\u003c')}</script><script type="module" src="/src/client.js"></script></head><body>${header(path)}<main id="main" tabindex="-1">${content(path)}</main>${footer()}</body></html>`;}

